from typing import Callable
from datetime import date
import sympy as sp
from pathlib import Path

from .sympy_3p2i import sympy_3p2i_fk, sympy_3p2i_ik
from .utils import _JnpPrinter, _NumbaPrinter


def generate(
        solver: str, # "jax" or "numba"
        kin: dict, 
        module_name: str,
        codegen_id: str
        ) -> tuple[Callable, Callable]:
    family = _detect_family(kin)
    sympy_tuple_fk, sympy_tuple_ik = _sympy_kin_to_cse(kin, family)
    code = _generate_code(solver, codegen_id, sympy_tuple_fk, sympy_tuple_ik)
    _emit_file(module_name, code)


def _detect_family(kin: dict) -> str:
    # TODO implement
    return "3p2i"

def _sympy_kin_to_cse(kin: dict, family: str):
    if family == "3p2i":
        return sympy_3p2i_fk(kin), sympy_3p2i_ik(kin)
    else:
        raise NotImplementedError

def _generate_code(solver, codegen_id, sympy_tuple_fk, sympy_tuple_ik):
    fk_input_syms, fk_all_syms, fk_const_repl, fk_global_repl, fk_global_red, fk_param_map = sympy_tuple_fk
    ik_input_syms, ik_all_syms, ik_const_repl, ik_global_repl, ik_global_red, ik_branch_joints, ik_param_map = sympy_tuple_ik
    assert len(ik_branch_joints) == 8

    code_head = [
        f'# AUTO-GENERATED by jaik.kinematics.codegen — do not edit',
        f'# Robot: {codegen_id}  |  Family: ...  |  Generated: {date.today()}',
    ]

    if solver == "jax":
        printer = _JnpPrinter()
        def emit(expr):
            return printer.doprint(expr)
        code_import, code_fk_header, code_fk_return, code_ik_header, code_ik_return = _get_surroinding_jax(ik_branch_joints, codegen_id, emit)

    elif solver == "numba":
        printer = _NumbaPrinter()
        def emit(expr):
            return printer.doprint(expr)
        code_import, code_fk_header, code_fk_return, code_ik_header, code_ik_return = _get_surroinding_numba(ik_branch_joints, codegen_id, emit)
    else:
        raise ValueError

    code_fk = []
        # ── Robot Parameters (Constants) ──
    for symbol, value in fk_param_map.items():
        code_fk.append(f"    {symbol} = {value}")
    code_fk.append('')

    # -- Constant replacements --
    for sym, expr in fk_const_repl:
        code_fk.append(f'    {sym} = {emit(expr)}')
    code_fk.append('')

    # -- Actual runtime calculations --
    sym_names = [str(s) for s in fk_input_syms]
    for i in range(6):
        code_fk.append(f'    {sym_names[i]} = sq[{i}]')
    for i in range(6):
        code_fk.append(f'    {sym_names[6+i]} = cq[{i}]')
    code_fk.append('')

    # All globally shared subexpressions first (sin/cos of boundary angles, etc.)
    # TODO: Bit of a janky way to get the order right, but it works for now..
    code_fk.append('    # ── global CSE: shared subexpressions + stage outputs ──')
    for sym, expr in fk_global_repl:
        x_ind_normal = get_max_x(sym)
        code_fk.append(f'    {sym} = {emit(expr)}')
        for sym, red_expr in zip(fk_all_syms, fk_global_red):
            x_ind_staged = get_max_x(red_expr)
            if x_ind_staged == x_ind_normal:
                code_fk.append(f'    {sym} = {emit(red_expr)}')
    code_fk.append('')

    code_ik = []

    # ── Robot Parameters (Constants) ──
    for symbol, value in ik_param_map.items():
        code_ik.append(f"    {symbol} = {value}")
    code_ik.append('')

    # -- Constant replacements --
    for sym, expr in ik_const_repl:
        code_ik.append(f'    {sym} = {emit(expr)}')
    code_ik.append('')

    # -- Actual runtime calculations --
    sym_names = [str(s) for s in ik_input_syms]
    for i in range(3):
        for j in range(3):
            code_ik.append(f'    {sym_names[i*3+j]} = R_06[{i}, {j}]')
    for i in range(3):
        code_ik.append(f'    {sym_names[9+i]} = p_0T[{i}]')
    code_ik.append('')

    # All globally shared subexpressions first (sin/cos of boundary angles, etc.)
    # TODO: Bit of a janky way to get the order right, but it works for now..
    code_ik.append('    # ── global CSE: shared subexpressions + stage outputs ──')
    for sym, expr in ik_global_repl:
        x_ind_normal = get_max_x(sym)
        code_ik.append(f'    {sym} = {emit(expr)}')
        for sym, red_expr in zip(ik_all_syms, ik_global_red):
            x_ind_staged = get_max_x(red_expr)
            if x_ind_staged == x_ind_normal:
                code_ik.append(f'    {sym} = {emit(red_expr)}')
    code_ik.append('')

    
    code = (code_head + code_import + 
            code_fk_header + code_fk + code_fk_return + 
            code_ik_header + code_ik + code_ik_return)
    return code

def get_max_x(sym) -> int:
    """
    Finds the maximum integer 'n' for all symbols following the pattern 'xn'.
    Works for both single symbols and complex expressions.
    """
    max_x = -1
    
    # .atoms(sp.Symbol) retrieves all unique variables in the expression
    for atom in sym.atoms(sp.Symbol):
        name = atom.name
        # Check if the name starts with 'x' followed by digits
        if name.startswith('x') and name[1:].isdigit():
            index = int(name[1:])
            if index > max_x:
                max_x = index
                
    return max_x

def _get_surroinding_jax(branch_joints, codegen_id, emit):
    code_import = [
        'import jax.numpy as jnp',
        'from jaxtyping import Float, Bool, Array, jaxtyped',
        'from beartype import beartype',
        '',
        '',
    ]
    code_fk_header = [
        '@jaxtyped(typechecker=beartype)',
        'def fk(sq, cq):',
    ]
    code_fk_return = [
        '    R = jnp.array([[r11, r12, r13], [r21, r22, r23], [r31, r32, r33]])',
        '    p = jnp.array([p1, p2, p3])',
        '    return R, p',
        '',
        '',
    ]
    code_ik_header = [
        '@jaxtyped(typechecker=beartype)',
        f'def ik_full(',
        '    R_06: Float[Array, "3 3"],',
        '    p_0T: Float[Array, "3"],',
        ') -> tuple[Float[Array, "6 8"], Float[Array, "6 8"], Bool[Array, "8"]]:',
        f'    """CSE-generated IK for {codegen_id}.',
        f'    Returns (sinQ, cosQ, valid): sinQ, cosQ are (6,8), valid is (8,) bool.',
        f'    NaN entries mark infeasible branches."""',
        '',
    ]

    code_ik_return = []
    code_ik_return.append('    sq = jnp.array([')
    for j in range(6):
        row = ', '.join(emit(branch_joints[b][2*j]) for b in range(8))
        code_ik_return.append(f'        [{row}],')
    code_ik_return.append('    ])  # (6, 8)')

    code_ik_return.append('    cq = jnp.array([')
    for j in range(6):
        row = ', '.join(emit(branch_joints[b][2*j+1]) for b in range(8))
        code_ik_return.append(f'        [{row}],')
    code_ik_return.append('    ])  # (6, 8)')

    code_ik_return += [
        '    valid = ~(jnp.isnan(sq) | jnp.isnan(cq)).any(axis=0)',
        '    return sq, cq, valid',
        '',
    ]
    return code_import, code_fk_header, code_fk_return, code_ik_header, code_ik_return

def _get_surroinding_numba(branch_joints, codegen_id, emit):
    code_import = [
        'import numpy as np',
        'from numba import njit',
        '',
        '',
    ]
    code_fk_header = [
        '@njit',
        'def fk(sq, cq):',
    ]
    code_fk_return = [
        '    R = np.array([[r11, r12, r13], [r21, r22, r23], [r31, r32, r33]])',
        '    p = np.array([p1, p2, p3])',
        '    return R, p',
        '',
        '',
    ]
    code_ik_header = [
        '@njit',
        f'def ik_full(',
        '    R_06: np.ndarray,',
        '    p_0T: np.ndarray,',
        ') -> tuple[np.ndarray, np.ndarray, np.ndarray]:',
        f'    """CSE-generated IK for {codegen_id}.',
        f'    Returns (sinQ, cosQ, valid): sinQ, cosQ are (6,8), valid is (8,) bool.',
        f'    NaN entries mark infeasible branches."""',
        '',
    ]

    code_ik_return = []
    code_ik_return.append('    sq = np.array([')
    for j in range(6):
        row = ', '.join(emit(branch_joints[b][2*j]) for b in range(8))
        code_ik_return.append(f'        [{row}],')
    code_ik_return.append('    ])  # (6, 8)')

    code_ik_return.append('    cq = np.array([')
    for j in range(6):
        row = ', '.join(emit(branch_joints[b][2*j+1]) for b in range(8))
        code_ik_return.append(f'        [{row}],')
    code_ik_return.append('    ])  # (6, 8)')

    code_ik_return += [
        '    valid = np.empty(8, dtype=np.bool_)',
        '    for i in range(8):',
        '        valid[i] = not (np.any(np.isnan(sq[:, i])) or np.any(np.isnan(cq[:, i])))',
        '    return sq, cq, valid',
        '',
    ]
    return code_import, code_fk_header, code_fk_return, code_ik_header, code_ik_return

def _emit_file(module_name: str, code):
    rel_path = Path(*module_name.split(".")).with_suffix(".py")
    out_path = Path(__file__).parent.parent.parent / rel_path
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text('\n'.join(code))
    print(f"  Written: {out_path} ({len(code)} lines)")