from typing import Callable
from datetime import date
import sympy as sp
from pathlib import Path

from .sympy_3p2i import sympy_3p2i_fk, sympy_3p2i_ik
from .utils import _JnpPrinter, _NumbaPrinter


def generate(
        solver: str, # "jax" or "numba"
        kin: dict, 
        module_name: str,
        codegen_id: str
        ) -> tuple[Callable, Callable]:
    family = _detect_family(kin)
    sympy_tuple_fk, sympy_tuple_ik = _sympy_kin_to_cse(kin, family)
    code = _generate_code(solver, codegen_id, sympy_tuple_fk, sympy_tuple_ik)
    _emit_file(module_name, code)


def _detect_family(kin: dict) -> str:
    # TODO implement
    return "3p2i"

def _sympy_kin_to_cse(kin: dict, family: str):
    if family == "3p2i":
        return sympy_3p2i_fk(kin), sympy_3p2i_ik(kin)
    else:
        raise NotImplementedError


def _generate_code(solver, codegen_id, sympy_tuple_fk, sympy_tuple_ik):
    # fk_input_syms, fk_all_syms, fk_const_repl, fk_global_repl, fk_global_red, fk_param_map = sympy_tuple_fk
    fk_input_syms, fk_all_syms, fk_const_repl, fk_global_repl, fk_global_red, fk_branch_joints, fk_param_map, fk_alias_map = sympy_tuple_fk
    ik_input_syms, ik_all_syms, ik_const_repl, ik_global_repl, ik_global_red, ik_branch_joints, ik_param_map, ik_alias_map = sympy_tuple_ik
    assert len(ik_branch_joints) == 8

    # ── Printer setup ─────────────────────────────────────────────────────────
    if solver == "jax":
        printer = _JnpPrinter()
        code_import, code_fk_header, code_fk_return, code_ik_header, code_ik_return = \
            _get_surroinding_jax(ik_branch_joints, codegen_id, printer.doprint)
    elif solver == "numba":
        printer = _NumbaPrinter()
        code_import, code_fk_header, code_fk_return, code_ik_header, code_ik_return = \
            _get_surroinding_numba(ik_branch_joints, codegen_id, printer.doprint)
    else:
        raise ValueError(f"Unknown solver: {solver!r}")

    emit = printer.doprint

    code_head = [
        f'# AUTO-GENERATED by jaik.kinematics.codegen — do not edit',
        f'# Robot: {codegen_id}  |  Generated: {date.today()}',
    ]

    # ── FK ────────────────────────────────────────────────────────────────────
    code_fk = [
        *_emit_param_map(fk_param_map, emit),
        *_emit_const_repl(fk_const_repl, emit),   # ← c0, c1, c2...
        *_emit_input_unpack_fk(fk_input_syms),
        '    # ── global CSE: shared subexpressions + stage outputs ──',
        *_emit_cse_interleaved(fk_global_repl, fk_all_syms, fk_global_red, emit),
        '    # ── aliases ──',
        *_emit_aliases(fk_alias_map),
    ]

    # ── IK ────────────────────────────────────────────────────────────────────
    code_ik = [
        *_emit_param_map(ik_param_map, emit),
        *_emit_const_repl(ik_const_repl, emit),   # ← c0, c1, c2...
        *_emit_input_unpack_ik(ik_input_syms),
        '    # ── global CSE: shared subexpressions + stage outputs ──',
        *_emit_cse_interleaved(ik_global_repl, ik_all_syms, ik_global_red, emit),
        '    # ── aliases ──',
        *_emit_aliases(ik_alias_map),
    ]

    return (code_head + code_import +
            code_fk_header + code_fk + code_fk_return +
            code_ik_header + code_ik + code_ik_return)


# ── Emission helpers ───────────────────────────────────────────────────────────

def _emit_param_map(param_map, emit) -> list[str]:
    return [f'    {sym} = {val}' for sym, val in param_map.items()] + ['']

def _emit_const_repl(const_repl, emit) -> list[str]:
    return [f'    {sym} = {emit(expr)}' for sym, expr in const_repl] + ['']

def _emit_input_unpack_fk(input_syms) -> list[str]:
    names = [str(s) for s in input_syms]  # sq1..sq6, cq1..cq6
    lines = (
        [f'    {names[i]} = sq[{i}]'   for i in range(6)] +
        [f'    {names[6+i]} = cq[{i}]' for i in range(6)]
    )
    return lines + ['']

def _emit_input_unpack_ik(input_syms) -> list[str]:
    names = [str(s) for s in input_syms]
    lines = (
        [f'    {names[i*3+j]} = R_06[{i}, {j}]' for i in range(3) for j in range(3)] +
        [f'    {names[9+i]} = p_0T[{i}]'         for i in range(3)]
    )
    return lines + ['']

def _emit_cse_interleaved(global_repl, all_syms, global_red, emit) -> list[str]:
    # Build a combined ordered list of (sym, expr) for everything
    all_assignments = list(global_repl) + list(zip(all_syms, global_red))
    
    # Map sym -> expr for all assignments
    sym_to_expr = {sym: expr for sym, expr in all_assignments}
    known = set(sym_to_expr)

    # Topological sort by dependency
    emitted = set()
    lines = []

    def emit_sym(sym):
        if sym in emitted or sym not in known:
            return
        # Emit dependencies first
        for dep in sym_to_expr[sym].free_symbols:
            if dep in known and dep not in emitted:
                emit_sym(dep)
        lines.append(f'    {sym} = {emit(sym_to_expr[sym])}')
        emitted.add(sym)

    for sym, _ in all_assignments:
        emit_sym(sym)

    return lines + ['']

def _emit_aliases(alias_map) -> list[str]:
    lines = []
    for sym, (coeff, ref) in alias_map.items():
        rhs = str(ref) if coeff == 1 else f'-{ref}'
        lines.append(f'    {sym} = {rhs}')
    return lines + ['']


def _get_surroinding_jax(branch_joints, codegen_id, emit):
    code_import = [
        'import jax.numpy as jnp',
        'from jaxtyping import Float, Bool, Array, jaxtyped',
        'from beartype import beartype',
        '',
        '',
    ]
    code_fk_header = [
        '@jaxtyped(typechecker=beartype)',
        'def fk(sq, cq):',
    ]
    code_fk_return = []
    code_fk_return.append('    R = jnp.array([')
    for i in range(3):
        row = ', '.join(f'r{i+1}{j+1}' for j in range(3))
        code_fk_return.append(f'        [{row}],')
    code_fk_return.append('    ])  # (3, 3)')
    code_fk_return += [
        '    p = jnp.array([p1, p2, p3])  # (3,)',
        '    return R, p',
        '',
    ]

    code_ik_header = [
        '@jaxtyped(typechecker=beartype)',
        f'def ik_full(',
        '    R_06: Float[Array, "3 3"],',
        '    p_0T: Float[Array, "3"],',
        ') -> tuple[Float[Array, "6 8"], Float[Array, "6 8"], Bool[Array, "8"]]:',
        f'    """CSE-generated IK for {codegen_id}.',
        f'    Returns (sinQ, cosQ, valid): sinQ, cosQ are (6,8), valid is (8,) bool.',
        f'    NaN entries mark infeasible branches."""',
        '',
    ]

    code_ik_return = []
    code_ik_return.append('    sq = jnp.array([')
    for j in range(6):
        row = ', '.join(emit(branch_joints[b][j][0]) for b in range(8))
        code_ik_return.append(f'        [{row}],')
    code_ik_return.append('    ])  # (6, 8)')

    code_ik_return.append('    cq = jnp.array([')
    for j in range(6):
        row = ', '.join(emit(branch_joints[b][j][1]) for b in range(8))
        code_ik_return.append(f'        [{row}],')
    code_ik_return.append('    ])  # (6, 8)')

    code_ik_return += [
        '    valid = ~(jnp.isnan(sq) | jnp.isnan(cq)).any(axis=0)',
        '    return sq, cq, valid',
        '',
    ]
    return code_import, code_fk_header, code_fk_return, code_ik_header, code_ik_return

def _get_surroinding_numba(branch_joints, codegen_id, emit):
    code_import = [
        'import numpy as np',
        'from numba import njit',
        '',
        '',
    ]
    code_fk_header = [
        '@njit',
        'def fk(sq, cq):',
    ]
    code_fk_return = []
    code_fk_return.append('    R = np.array([')
    for i in range(3):
        row = ', '.join(f'r{i+1}{j+1}' for j in range(3))
        code_fk_return.append(f'        [{row}],')
    code_fk_return.append('    ])  # (3, 3)')
    code_fk_return += [
        '    p = np.array([p1, p2, p3])  # (3,)',
        '    return R, p',
        '',
    ]
    code_ik_header = [
        '@njit',
        f'def ik_full(',
        '    R_06: np.ndarray,',
        '    p_0T: np.ndarray,',
        ') -> tuple[np.ndarray, np.ndarray, np.ndarray]:',
        f'    """CSE-generated IK for {codegen_id}.',
        f'    Returns (sinQ, cosQ, valid): sinQ, cosQ are (6,8), valid is (8,) bool.',
        f'    NaN entries mark infeasible branches."""',
        '',
    ]

    code_ik_return = []
    code_ik_return.append('    sq = np.array([')
    for j in range(6):
        row = ', '.join(emit(branch_joints[b][j][0]) for b in range(8))
        code_ik_return.append(f'        [{row}],')
    code_ik_return.append('    ])  # (6, 8)')

    code_ik_return.append('    cq = np.array([')
    for j in range(6):
        row = ', '.join(emit(branch_joints[b][j][1]) for b in range(8))
        code_ik_return.append(f'        [{row}],')
    code_ik_return.append('    ])  # (6, 8)')

    code_ik_return += [
        '    valid = np.empty(8, dtype=np.bool_)',
        '    for i in range(8):',
        '        valid[i] = not (np.any(np.isnan(sq[:, i])) or np.any(np.isnan(cq[:, i])))',
        '    return sq, cq, valid',
        '',
    ]
    return code_import, code_fk_header, code_fk_return, code_ik_header, code_ik_return

def _emit_file(module_name: str, code):
    rel_path = Path(*module_name.split(".")).with_suffix(".py")
    out_path = Path(__file__).parent.parent.parent / rel_path
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text('\n'.join(code))
    print(f"  Written: {out_path} ({len(code)} lines)")