# AUTO-GENERATED by jaik.kinematics.codegen — do not edit
# Robot: ur10e  |  Family: ...  |  Generated: 2026-04-06
import numpy as np
from numba import njit


@njit
def fk(sq, cq):
    P03 = 0.1807
    P21 = -0.6127
    P31 = -0.57155
    P42 = -0.17415000000000003
    P43 = -0.11984999999999998
    P62 = -0.11655


    sq1 = sq[0]
    sq2 = sq[1]
    sq3 = sq[2]
    sq4 = sq[3]
    sq5 = sq[4]
    sq6 = sq[5]
    cq1 = cq[0]
    cq2 = cq[1]
    cq3 = cq[2]
    cq4 = cq[3]
    cq5 = cq[4]
    cq6 = cq[5]

    # ── global CSE: shared subexpressions + stage outputs ──
    x0 = cq2*sq3 + cq3*sq2
    x1 = cq2*cq3 - sq2*sq3
    x2 = cq4*x0 + sq4*x1
    x3 = cq1*x2
    x4 = sq1*sq5
    x5 = cq4*x1 - sq4*x0
    x6 = cq1*cq5
    x7 = x4 + x5*x6
    r11 = cq6*x7 - sq6*x3
    r13 = -cq6*x3 - sq6*x7
    x8 = cq5*sq1
    x9 = cq1*sq5
    x10 = x5*x9 - x8
    r12 = x10
    x11 = sq1*x2
    x12 = -x5*x8 + x9
    r21 = -cq6*x12 - sq6*x11
    r23 = -cq6*x11 + sq6*x12
    x13 = x4*x5 + x6
    r22 = x13
    x14 = cq5*x2
    r31 = cq6*x14 + sq6*x5
    r33 = cq6*x5 - sq6*x14
    x15 = sq5*x2
    r32 = x15
    p3 = P03 + P21*sq2 + P31*x0 + P43*x5 + P62*x15
    x16 = P21*cq2
    x17 = P31*x1
    p1 = -P42*sq1 - P43*x3 + P62*x10 + cq1*x16 + cq1*x17
    p2 = P42*cq1 - P43*x11 + P62*x13 + sq1*x16 + sq1*x17

    R = np.array([[r11, r12, r13], [r21, r22, r23], [r31, r32, r33]])
    p = np.array([p1, p2, p3])
    return R, p


@njit
def ik_full(
    R_06: np.ndarray,
    p_0T: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """CSE-generated IK for ur10e.
    Returns (sinQ, cosQ, valid): sinQ, cosQ are (6,8), valid is (8,) bool.
    NaN entries mark infeasible branches."""

    P03 = 0.1807
    P21 = -0.6127
    P31 = -0.57155
    P42 = -0.17415000000000003
    P43 = -0.11984999999999998
    P62 = -0.11655

    c0 = -((P42) ** 2)
    c1 = ((P62) ** 2)
    c2 = ((P21) ** 2)
    c3 = ((P31) ** 2)
    c4 = ((P21) ** 4) + ((P31) ** 4) - 2*c2*c3
    c5 = (0.5)/(P21*P31)
    c6 = -c2 - c3

    r11 = R_06[0, 0]
    r12 = R_06[0, 1]
    r13 = R_06[0, 2]
    r21 = R_06[1, 0]
    r22 = R_06[1, 1]
    r23 = R_06[1, 2]
    r31 = R_06[2, 0]
    r32 = R_06[2, 1]
    r33 = R_06[2, 2]
    p1 = p_0T[0]
    p2 = p_0T[1]
    p3 = p_0T[2]

    # ── global CSE: shared subexpressions + stage outputs ──
    x0 = P62*r12
    x1 = -p1 + x0
    x2 = P42*x1
    x3 = P62*r22
    x4 = -p2 + x3
    x5 = ((r12) ** 2)
    x6 = ((r22) ** 2)
    x7 = np.sqrt(c0 + c1*x5 + c1*x6 + ((p1) ** 2) - 2*p1*x0 + ((p2) ** 2) - 2*p2*x3)
    x8 = x4*x7
    x9 = x2 + x8
    x10 = P42*x4
    x11 = x1*x7
    x12 = x10 - x11
    x13 = (1.0 / np.sqrt(((x12) ** 2) + ((x9) ** 2)))
    s_t1_0 = x13*x9
    c_t1_0 = -x12*x13
    x14 = x2 - x8
    x15 = x10 + x11
    x16 = (1.0 / np.sqrt(((x14) ** 2) + ((x15) ** 2)))
    s_t1_1 = x14*x16
    c_t1_1 = -x15*x16
    x17 = ((c_t1_0) ** 2)
    x18 = np.sqrt(2*c_t1_0*r12*r22*s_t1_0 - x17*x6 - x5*(1 - x17) + 1)
    s_t5_0_q10 = x18
    x19 = c_t1_0*r22 - r12*s_t1_0
    c_t5_1_q10 = x19
    x20 = ((c_t1_1) ** 2)
    x21 = np.sqrt(2*c_t1_1*r12*r22*s_t1_1 - x20*x6 - x5*(1 - x20) + 1)
    s_t5_0_q11 = x21
    x22 = c_t1_1*r22 - r12*s_t1_1
    c_t5_1_q11 = x22
    x23 = np.sign(s_t5_0_q10)
    x24 = ((r32) ** 2)
    x25 = c_t1_0*r12 + r22*s_t1_0
    x26 = (1.0 / np.sqrt(x24 + ((x25) ** 2)))
    x27 = r32*x26
    s_th14_q10_q50 = x23*x27
    x28 = x25*x26
    c_th14_q10_q50 = x23*x28
    x29 = c_t1_0*r23 - r13*s_t1_0
    x30 = c_t1_0*r21 - r11*s_t1_0
    x31 = (1.0 / np.sqrt(((x29) ** 2) + ((x30) ** 2)))
    x32 = x23*x31
    s_q6_q10_q50 = x29*x32
    c_q6_q10_q50 = -x30*x32
    x33 = -np.sign(s_t5_0_q10)
    s_th14_q10_q51 = x27*x33
    c_th14_q10_q51 = x28*x33
    x34 = x31*x33
    s_q6_q10_q51 = x29*x34
    c_q6_q10_q51 = -x30*x34
    x35 = np.sign(s_t5_0_q11)
    x36 = c_t1_1*r12 + r22*s_t1_1
    x37 = (1.0 / np.sqrt(x24 + ((x36) ** 2)))
    x38 = r32*x37
    s_th14_q11_q50 = x35*x38
    x39 = x36*x37
    c_th14_q11_q50 = x35*x39
    x40 = c_t1_1*r23 - r13*s_t1_1
    x41 = c_t1_1*r21 - r11*s_t1_1
    x42 = (1.0 / np.sqrt(((x40) ** 2) + ((x41) ** 2)))
    x43 = x35*x42
    s_q6_q11_q50 = x40*x43
    c_q6_q11_q50 = -x41*x43
    x44 = -np.sign(s_t5_0_q11)
    s_th14_q11_q51 = x38*x44
    c_th14_q11_q51 = x39*x44
    x45 = x42*x44
    s_q6_q11_q51 = x40*x45
    c_q6_q11_q51 = -x41*x45
    x46 = -c4
    x47 = P03 + P62*r32 - p3
    x48 = P43*c_th14_q10_q50 + x47
    x49 = ((P42 + c_t1_0*x4 - s_t1_0*x1) ** 2)
    x50 = c_t1_0*x1 + s_t1_0*x4
    x51 = -P43*s_th14_q10_q50 + x50
    x52 = ((x48) ** 2) + x49 + ((x51) ** 2)
    x53 = 2*x52
    x54 = c5*np.sqrt(c2*x53 + c3*x53 + x46 - ((x52) ** 2))
    s_t3_0_q10_q50 = x54
    x55 = c5*(c6 + x52)
    c_t3_1_q10_q50 = x55
    x56 = P43*c_th14_q10_q51 + x47
    x57 = -P43*s_th14_q10_q51 + x50
    x58 = x49 + ((x56) ** 2) + ((x57) ** 2)
    x59 = 2*x58
    x60 = c5*np.sqrt(c2*x59 + c3*x59 + x46 - ((x58) ** 2))
    s_t3_0_q10_q51 = x60
    x61 = c5*(c6 + x58)
    c_t3_1_q10_q51 = x61
    x62 = P43*c_th14_q11_q50 + x47
    x63 = ((P42 + c_t1_1*x4 - s_t1_1*x1) ** 2)
    x64 = c_t1_1*x1 + s_t1_1*x4
    x65 = -P43*s_th14_q11_q50 + x64
    x66 = ((x62) ** 2) + x63 + ((x65) ** 2)
    x67 = 2*x66
    x68 = c5*np.sqrt(c2*x67 + c3*x67 + x46 - ((x66) ** 2))
    s_t3_0_q11_q50 = x68
    x69 = c5*(c6 + x66)
    c_t3_1_q11_q50 = x69
    x70 = P43*c_th14_q11_q51 + x47
    x71 = -P43*s_th14_q11_q51 + x64
    x72 = x63 + ((x70) ** 2) + ((x71) ** 2)
    x73 = 2*x72
    x74 = c5*np.sqrt(c2*x73 + c3*x73 + x46 - ((x72) ** 2))
    s_t3_0_q11_q51 = x74
    x75 = c5*(c6 + x72)
    c_t3_1_q11_q51 = x75
    x76 = P21 + P31*c_t3_1_q10_q50
    x77 = P31*s_t3_0_q10_q50
    x78 = -x48*x76 + x51*x77
    x79 = x48*x77 + x51*x76
    x80 = (1.0 / np.sqrt(((x78) ** 2) + ((x79) ** 2)))
    s_q2_b000 = x78*x80
    c_q2_b000 = -x79*x80
    x81 = c_th14_q10_q50*x78 + s_th14_q10_q50*x79
    x82 = c_th14_q10_q50*x79 - s_th14_q10_q50*x78
    s_q4_b000 = -x80*(c_t3_1_q10_q50*x81 - s_t3_0_q10_q50*x82)
    c_q4_b000 = -x80*(c_t3_1_q10_q50*x82 + s_t3_0_q10_q50*x81)
    x83 = P21 + P31*c_t3_1_q10_q50
    x84 = -P31*s_t3_0_q10_q50
    x85 = -x48*x83 + x51*x84
    x86 = x48*x84 + x51*x83
    x87 = (1.0 / np.sqrt(((x85) ** 2) + ((x86) ** 2)))
    s_q2_b001 = x85*x87
    c_q2_b001 = -x86*x87
    x88 = c_th14_q10_q50*x85 + s_th14_q10_q50*x86
    x89 = c_th14_q10_q50*x86 - s_th14_q10_q50*x85
    s_q4_b001 = -x87*(c_t3_1_q10_q50*x88 + s_t3_0_q10_q50*x89)
    c_q4_b001 = -x87*(c_t3_1_q10_q50*x89 - s_t3_0_q10_q50*x88)
    x90 = P21 + P31*c_t3_1_q10_q51
    x91 = P31*s_t3_0_q10_q51
    x92 = -x56*x90 + x57*x91
    x93 = x56*x91 + x57*x90
    x94 = (1.0 / np.sqrt(((x92) ** 2) + ((x93) ** 2)))
    s_q2_b010 = x92*x94
    c_q2_b010 = -x93*x94
    x95 = c_th14_q10_q51*x92 + s_th14_q10_q51*x93
    x96 = c_th14_q10_q51*x93 - s_th14_q10_q51*x92
    s_q4_b010 = -x94*(c_t3_1_q10_q51*x95 - s_t3_0_q10_q51*x96)
    c_q4_b010 = -x94*(c_t3_1_q10_q51*x96 + s_t3_0_q10_q51*x95)
    x97 = P21 + P31*c_t3_1_q10_q51
    x98 = -P31*s_t3_0_q10_q51
    x99 = -x56*x97 + x57*x98
    x100 = x56*x98 + x57*x97
    x101 = (1.0 / np.sqrt(((x100) ** 2) + ((x99) ** 2)))
    s_q2_b011 = x101*x99
    c_q2_b011 = -x100*x101
    x102 = c_th14_q10_q51*x99 + s_th14_q10_q51*x100
    x103 = c_th14_q10_q51*x100 - s_th14_q10_q51*x99
    s_q4_b011 = -x101*(c_t3_1_q10_q51*x102 + s_t3_0_q10_q51*x103)
    c_q4_b011 = -x101*(c_t3_1_q10_q51*x103 - s_t3_0_q10_q51*x102)
    x104 = P21 + P31*c_t3_1_q11_q50
    x105 = P31*s_t3_0_q11_q50
    x106 = -x104*x62 + x105*x65
    x107 = x104*x65 + x105*x62
    x108 = (1.0 / np.sqrt(((x106) ** 2) + ((x107) ** 2)))
    s_q2_b100 = x106*x108
    c_q2_b100 = -x107*x108
    x109 = c_th14_q11_q50*x106 + s_th14_q11_q50*x107
    x110 = c_th14_q11_q50*x107 - s_th14_q11_q50*x106
    s_q4_b100 = -x108*(c_t3_1_q11_q50*x109 - s_t3_0_q11_q50*x110)
    c_q4_b100 = -x108*(c_t3_1_q11_q50*x110 + s_t3_0_q11_q50*x109)
    x111 = P21 + P31*c_t3_1_q11_q50
    x112 = -P31*s_t3_0_q11_q50
    x113 = -x111*x62 + x112*x65
    x114 = x111*x65 + x112*x62
    x115 = (1.0 / np.sqrt(((x113) ** 2) + ((x114) ** 2)))
    s_q2_b101 = x113*x115
    c_q2_b101 = -x114*x115
    x116 = c_th14_q11_q50*x113 + s_th14_q11_q50*x114
    x117 = c_th14_q11_q50*x114 - s_th14_q11_q50*x113
    s_q4_b101 = -x115*(c_t3_1_q11_q50*x116 + s_t3_0_q11_q50*x117)
    c_q4_b101 = -x115*(c_t3_1_q11_q50*x117 - s_t3_0_q11_q50*x116)
    x118 = P21 + P31*c_t3_1_q11_q51
    x119 = P31*s_t3_0_q11_q51
    x120 = -x118*x70 + x119*x71
    x121 = x118*x71 + x119*x70
    x122 = (1.0 / np.sqrt(((x120) ** 2) + ((x121) ** 2)))
    s_q2_b110 = x120*x122
    c_q2_b110 = -x121*x122
    x123 = c_th14_q11_q51*x120 + s_th14_q11_q51*x121
    x124 = c_th14_q11_q51*x121 - s_th14_q11_q51*x120
    s_q4_b110 = -x122*(c_t3_1_q11_q51*x123 - s_t3_0_q11_q51*x124)
    c_q4_b110 = -x122*(c_t3_1_q11_q51*x124 + s_t3_0_q11_q51*x123)
    x125 = P21 + P31*c_t3_1_q11_q51
    x126 = -P31*s_t3_0_q11_q51
    x127 = -x125*x70 + x126*x71
    x128 = x125*x71 + x126*x70
    x129 = (1.0 / np.sqrt(((x127) ** 2) + ((x128) ** 2)))
    s_q2_b111 = x127*x129
    c_q2_b111 = -x128*x129
    x130 = c_th14_q11_q51*x127 + s_th14_q11_q51*x128
    x131 = c_th14_q11_q51*x128 - s_th14_q11_q51*x127
    s_q4_b111 = -x129*(c_t3_1_q11_q51*x130 + s_t3_0_q11_q51*x131)
    c_q4_b111 = -x129*(c_t3_1_q11_q51*x131 - s_t3_0_q11_q51*x130)

    # ----trivial----
    c_t5_0_q10 = 1*c_t5_1_q10
    s_t5_1_q10 = -1*s_t5_0_q10
    c_t5_0_q11 = 1*c_t5_1_q11
    s_t5_1_q11 = -1*s_t5_0_q11
    c_t3_0_q10_q50 = 1*c_t3_1_q10_q50
    s_t3_1_q10_q50 = -1*s_t3_0_q10_q50
    c_t3_0_q10_q51 = 1*c_t3_1_q10_q51
    s_t3_1_q10_q51 = -1*s_t3_0_q10_q51
    c_t3_0_q11_q50 = 1*c_t3_1_q11_q50
    s_t3_1_q11_q50 = -1*s_t3_0_q11_q50
    c_t3_0_q11_q51 = 1*c_t3_1_q11_q51
    s_t3_1_q11_q51 = -1*s_t3_0_q11_q51
    sq = np.array([
        [s_t1_0, s_t1_0, s_t1_0, s_t1_0, s_t1_1, s_t1_1, s_t1_1, s_t1_1],
        [s_q2_b000, s_q2_b001, s_q2_b010, s_q2_b011, s_q2_b100, s_q2_b101, s_q2_b110, s_q2_b111],
        [s_t3_0_q10_q50, s_t3_1_q10_q50, s_t3_0_q10_q51, s_t3_1_q10_q51, s_t3_0_q11_q50, s_t3_1_q11_q50, s_t3_0_q11_q51, s_t3_1_q11_q51],
        [s_q4_b000, s_q4_b001, s_q4_b010, s_q4_b011, s_q4_b100, s_q4_b101, s_q4_b110, s_q4_b111],
        [s_t5_0_q10, s_t5_0_q10, s_t5_1_q10, s_t5_1_q10, s_t5_0_q11, s_t5_0_q11, s_t5_1_q11, s_t5_1_q11],
        [s_q6_q10_q50, s_q6_q10_q50, s_q6_q10_q51, s_q6_q10_q51, s_q6_q11_q50, s_q6_q11_q50, s_q6_q11_q51, s_q6_q11_q51],
    ])  # (6, 8)
    cq = np.array([
        [c_t1_0, c_t1_0, c_t1_0, c_t1_0, c_t1_1, c_t1_1, c_t1_1, c_t1_1],
        [c_q2_b000, c_q2_b001, c_q2_b010, c_q2_b011, c_q2_b100, c_q2_b101, c_q2_b110, c_q2_b111],
        [c_t3_0_q10_q50, c_t3_1_q10_q50, c_t3_0_q10_q51, c_t3_1_q10_q51, c_t3_0_q11_q50, c_t3_1_q11_q50, c_t3_0_q11_q51, c_t3_1_q11_q51],
        [c_q4_b000, c_q4_b001, c_q4_b010, c_q4_b011, c_q4_b100, c_q4_b101, c_q4_b110, c_q4_b111],
        [c_t5_0_q10, c_t5_0_q10, c_t5_1_q10, c_t5_1_q10, c_t5_0_q11, c_t5_0_q11, c_t5_1_q11, c_t5_1_q11],
        [c_q6_q10_q50, c_q6_q10_q50, c_q6_q10_q51, c_q6_q10_q51, c_q6_q11_q50, c_q6_q11_q50, c_q6_q11_q51, c_q6_q11_q51],
    ])  # (6, 8)
    valid = np.empty(8, dtype=np.bool_)
    for i in range(8):
        valid[i] = not (np.any(np.isnan(sq[:, i])) or np.any(np.isnan(cq[:, i])))
    return sq, cq, valid
