# AUTO-GENERATED by jaik.kinematics.codegen — do not edit
# Robot: ur20  |  Family: ...  |  Generated: 2026-04-05
import numpy as np
from numba import njit


@njit
def fk(sq, cq):
    P03 = 0.2363
    P21 = -0.862
    P31 = -0.7287
    P42 = -0.20100000000000004
    P43 = -0.15929999999999997
    P62 = -0.1543


    sq1 = sq[0]
    sq2 = sq[1]
    sq3 = sq[2]
    sq4 = sq[3]
    sq5 = sq[4]
    sq6 = sq[5]
    cq1 = cq[0]
    cq2 = cq[1]
    cq3 = cq[2]
    cq4 = cq[3]
    cq5 = cq[4]
    cq6 = cq[5]

    # ── global CSE: shared subexpressions + stage outputs ──
    x0 = cq2*sq3 + cq3*sq2
    x1 = cq2*cq3 - sq2*sq3
    x2 = cq4*x0 + sq4*x1
    x3 = cq1*x2
    x4 = sq1*sq5
    x5 = cq4*x1 - sq4*x0
    x6 = cq1*cq5
    x7 = x4 + x5*x6
    r11 = cq6*x7 - sq6*x3
    r13 = -cq6*x3 - sq6*x7
    x8 = cq5*sq1
    x9 = cq1*sq5
    x10 = x5*x9 - x8
    r12 = x10
    x11 = sq1*x2
    x12 = -x5*x8 + x9
    r21 = -cq6*x12 - sq6*x11
    r23 = -cq6*x11 + sq6*x12
    x13 = x4*x5 + x6
    r22 = x13
    x14 = cq5*x2
    r31 = cq6*x14 + sq6*x5
    r33 = cq6*x5 - sq6*x14
    x15 = sq5*x2
    r32 = x15
    p3 = P03 + P21*sq2 + P31*x0 + P43*x5 + P62*x15
    x16 = P21*cq2
    x17 = P31*x1
    p1 = -P42*sq1 - P43*x3 + P62*x10 + cq1*x16 + cq1*x17
    p2 = P42*cq1 - P43*x11 + P62*x13 + sq1*x16 + sq1*x17

    R = np.array([[r11, r12, r13], [r21, r22, r23], [r31, r32, r33]])
    p = np.array([p1, p2, p3])
    return R, p


@njit
def ik_full(
    R_06: np.ndarray,
    p_0T: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """CSE-generated IK for ur20.
    Returns (sinQ, cosQ, valid): sinQ, cosQ are (6,8), valid is (8,) bool.
    NaN entries mark infeasible branches."""

    P03 = 0.2363
    P21 = -0.862
    P31 = -0.7287
    P42 = -0.20100000000000004
    P43 = -0.15929999999999997
    P62 = -0.1543

    c0 = -((P42) ** 2)
    c1 = ((P62) ** 2)
    c2 = ((P21) ** 2)
    c3 = ((P31) ** 2)
    c4 = ((P21) ** 4) + ((P31) ** 4) - 2*c2*c3
    c5 = (0.5)/(P21*P31)
    c6 = -c2 - c3

    r11 = R_06[0, 0]
    r12 = R_06[0, 1]
    r13 = R_06[0, 2]
    r21 = R_06[1, 0]
    r22 = R_06[1, 1]
    r23 = R_06[1, 2]
    r31 = R_06[2, 0]
    r32 = R_06[2, 1]
    r33 = R_06[2, 2]
    p1 = p_0T[0]
    p2 = p_0T[1]
    p3 = p_0T[2]

    # ── global CSE: shared subexpressions + stage outputs ──
    x0 = P62*r12
    x1 = -p1 + x0
    x2 = P42*x1
    x3 = P62*r22
    x4 = -p2 + x3
    x5 = ((r12) ** 2)
    x6 = ((r22) ** 2)
    x7 = np.sqrt(c0 + c1*x5 + c1*x6 + ((p1) ** 2) - 2*p1*x0 + ((p2) ** 2) - 2*p2*x3)
    x8 = x4*x7
    x9 = x2 + x8
    x10 = P42*x4
    x11 = x1*x7
    x12 = x10 - x11
    x13 = (1.0 / np.sqrt(((x12) ** 2) + ((x9) ** 2)))
    s_t1_0 = x13*x9
    c_t1_0 = -x12*x13
    x14 = x2 - x8
    x15 = x10 + x11
    x16 = (1.0 / np.sqrt(((x14) ** 2) + ((x15) ** 2)))
    s_t1_1 = x14*x16
    c_t1_1 = -x15*x16
    x17 = np.sqrt(-((c_t1_0) ** 2)*x6 + 2*c_t1_0*r12*r22*s_t1_0 - ((s_t1_0) ** 2)*x5 + 1)
    s_t5_0_q10 = x17
    s_t5_1_q10 = -x17
    x18 = c_t1_0*r22 - r12*s_t1_0
    c_t5_0_q10 = x18
    c_t5_1_q10 = x18
    x19 = np.sqrt(-((c_t1_1) ** 2)*x6 + 2*c_t1_1*r12*r22*s_t1_1 - ((s_t1_1) ** 2)*x5 + 1)
    s_t5_0_q11 = x19
    s_t5_1_q11 = -x19
    x20 = c_t1_1*r22 - r12*s_t1_1
    c_t5_0_q11 = x20
    c_t5_1_q11 = x20
    x21 = np.sign(s_t5_0_q10)
    x22 = ((r32) ** 2)
    x23 = c_t1_0*r12 + r22*s_t1_0
    x24 = (1.0 / np.sqrt(x22 + ((x23) ** 2)))
    x25 = r32*x24
    s_th14_q10_q50 = x21*x25
    x26 = x23*x24
    c_th14_q10_q50 = x21*x26
    x27 = c_t1_0*r23 - r13*s_t1_0
    x28 = c_t1_0*r21 - r11*s_t1_0
    x29 = (1.0 / np.sqrt(((x27) ** 2) + ((x28) ** 2)))
    x30 = x21*x29
    s_q6_q10_q50 = x27*x30
    c_q6_q10_q50 = -x28*x30
    x31 = np.sign(s_t5_1_q10)
    s_th14_q10_q51 = x25*x31
    c_th14_q10_q51 = x26*x31
    x32 = x29*x31
    s_q6_q10_q51 = x27*x32
    c_q6_q10_q51 = -x28*x32
    x33 = np.sign(s_t5_0_q11)
    x34 = c_t1_1*r12 + r22*s_t1_1
    x35 = (1.0 / np.sqrt(x22 + ((x34) ** 2)))
    x36 = r32*x35
    s_th14_q11_q50 = x33*x36
    x37 = x34*x35
    c_th14_q11_q50 = x33*x37
    x38 = c_t1_1*r23 - r13*s_t1_1
    x39 = c_t1_1*r21 - r11*s_t1_1
    x40 = (1.0 / np.sqrt(((x38) ** 2) + ((x39) ** 2)))
    x41 = x33*x40
    s_q6_q11_q50 = x38*x41
    c_q6_q11_q50 = -x39*x41
    x42 = np.sign(s_t5_1_q11)
    s_th14_q11_q51 = x36*x42
    c_th14_q11_q51 = x37*x42
    x43 = x40*x42
    s_q6_q11_q51 = x38*x43
    c_q6_q11_q51 = -x39*x43
    x44 = -c4
    x45 = P03 + P62*r32 - p3
    x46 = P43*c_th14_q10_q50 + x45
    x47 = ((P42 + c_t1_0*x4 - s_t1_0*x1) ** 2)
    x48 = c_t1_0*x1 + s_t1_0*x4
    x49 = -P43*s_th14_q10_q50 + x48
    x50 = ((x46) ** 2) + x47 + ((x49) ** 2)
    x51 = 2*x50
    x52 = c5*np.sqrt(c2*x51 + c3*x51 + x44 - ((x50) ** 2))
    s_t3_0_q10_q50 = x52
    s_t3_1_q10_q50 = -x52
    x53 = c5*(c6 + x50)
    c_t3_0_q10_q50 = x53
    c_t3_1_q10_q50 = x53
    x54 = P43*c_th14_q10_q51 + x45
    x55 = -P43*s_th14_q10_q51 + x48
    x56 = x47 + ((x54) ** 2) + ((x55) ** 2)
    x57 = 2*x56
    x58 = c5*np.sqrt(c2*x57 + c3*x57 + x44 - ((x56) ** 2))
    s_t3_0_q10_q51 = x58
    s_t3_1_q10_q51 = -x58
    x59 = c5*(c6 + x56)
    c_t3_0_q10_q51 = x59
    c_t3_1_q10_q51 = x59
    x60 = P43*c_th14_q11_q50 + x45
    x61 = ((P42 + c_t1_1*x4 - s_t1_1*x1) ** 2)
    x62 = c_t1_1*x1 + s_t1_1*x4
    x63 = -P43*s_th14_q11_q50 + x62
    x64 = ((x60) ** 2) + x61 + ((x63) ** 2)
    x65 = 2*x64
    x66 = c5*np.sqrt(c2*x65 + c3*x65 + x44 - ((x64) ** 2))
    s_t3_0_q11_q50 = x66
    s_t3_1_q11_q50 = -x66
    x67 = c5*(c6 + x64)
    c_t3_0_q11_q50 = x67
    c_t3_1_q11_q50 = x67
    x68 = P43*c_th14_q11_q51 + x45
    x69 = -P43*s_th14_q11_q51 + x62
    x70 = x61 + ((x68) ** 2) + ((x69) ** 2)
    x71 = 2*x70
    x72 = c5*np.sqrt(c2*x71 + c3*x71 + x44 - ((x70) ** 2))
    s_t3_0_q11_q51 = x72
    s_t3_1_q11_q51 = -x72
    x73 = c5*(c6 + x70)
    c_t3_0_q11_q51 = x73
    c_t3_1_q11_q51 = x73
    x74 = P21 + P31*c_t3_0_q10_q50
    x75 = P31*s_t3_0_q10_q50
    x76 = -x46*x74 + x49*x75
    x77 = x46*x75 + x49*x74
    x78 = (1.0 / np.sqrt(((x76) ** 2) + ((x77) ** 2)))
    s_q2_b000 = x76*x78
    c_q2_b000 = -x77*x78
    x79 = c_th14_q10_q50*x76 + s_th14_q10_q50*x77
    x80 = c_th14_q10_q50*x77 - s_th14_q10_q50*x76
    s_q4_b000 = x78*(-c_t3_0_q10_q50*x79 + s_t3_0_q10_q50*x80)
    c_q4_b000 = -x78*(c_t3_0_q10_q50*x80 + s_t3_0_q10_q50*x79)
    x81 = P21 + P31*c_t3_1_q10_q50
    x82 = P31*s_t3_1_q10_q50
    x83 = -x46*x81 + x49*x82
    x84 = x46*x82 + x49*x81
    x85 = (1.0 / np.sqrt(((x83) ** 2) + ((x84) ** 2)))
    s_q2_b001 = x83*x85
    c_q2_b001 = -x84*x85
    x86 = c_th14_q10_q50*x83 + s_th14_q10_q50*x84
    x87 = c_th14_q10_q50*x84 - s_th14_q10_q50*x83
    s_q4_b001 = x85*(-c_t3_1_q10_q50*x86 + s_t3_1_q10_q50*x87)
    c_q4_b001 = -x85*(c_t3_1_q10_q50*x87 + s_t3_1_q10_q50*x86)
    x88 = P21 + P31*c_t3_0_q10_q51
    x89 = P31*s_t3_0_q10_q51
    x90 = -x54*x88 + x55*x89
    x91 = x54*x89 + x55*x88
    x92 = (1.0 / np.sqrt(((x90) ** 2) + ((x91) ** 2)))
    s_q2_b010 = x90*x92
    c_q2_b010 = -x91*x92
    x93 = c_th14_q10_q51*x90 + s_th14_q10_q51*x91
    x94 = c_th14_q10_q51*x91 - s_th14_q10_q51*x90
    s_q4_b010 = x92*(-c_t3_0_q10_q51*x93 + s_t3_0_q10_q51*x94)
    c_q4_b010 = -x92*(c_t3_0_q10_q51*x94 + s_t3_0_q10_q51*x93)
    x95 = P21 + P31*c_t3_1_q10_q51
    x96 = P31*s_t3_1_q10_q51
    x97 = -x54*x95 + x55*x96
    x98 = x54*x96 + x55*x95
    x99 = (1.0 / np.sqrt(((x97) ** 2) + ((x98) ** 2)))
    s_q2_b011 = x97*x99
    c_q2_b011 = -x98*x99
    x100 = c_th14_q10_q51*x97 + s_th14_q10_q51*x98
    x101 = c_th14_q10_q51*x98 - s_th14_q10_q51*x97
    s_q4_b011 = x99*(-c_t3_1_q10_q51*x100 + s_t3_1_q10_q51*x101)
    c_q4_b011 = -x99*(c_t3_1_q10_q51*x101 + s_t3_1_q10_q51*x100)
    x102 = P21 + P31*c_t3_0_q11_q50
    x103 = P31*s_t3_0_q11_q50
    x104 = -x102*x60 + x103*x63
    x105 = x102*x63 + x103*x60
    x106 = (1.0 / np.sqrt(((x104) ** 2) + ((x105) ** 2)))
    s_q2_b100 = x104*x106
    c_q2_b100 = -x105*x106
    x107 = c_th14_q11_q50*x104 + s_th14_q11_q50*x105
    x108 = c_th14_q11_q50*x105 - s_th14_q11_q50*x104
    s_q4_b100 = x106*(-c_t3_0_q11_q50*x107 + s_t3_0_q11_q50*x108)
    c_q4_b100 = -x106*(c_t3_0_q11_q50*x108 + s_t3_0_q11_q50*x107)
    x109 = P21 + P31*c_t3_1_q11_q50
    x110 = P31*s_t3_1_q11_q50
    x111 = -x109*x60 + x110*x63
    x112 = x109*x63 + x110*x60
    x113 = (1.0 / np.sqrt(((x111) ** 2) + ((x112) ** 2)))
    s_q2_b101 = x111*x113
    c_q2_b101 = -x112*x113
    x114 = c_th14_q11_q50*x111 + s_th14_q11_q50*x112
    x115 = c_th14_q11_q50*x112 - s_th14_q11_q50*x111
    s_q4_b101 = x113*(-c_t3_1_q11_q50*x114 + s_t3_1_q11_q50*x115)
    c_q4_b101 = -x113*(c_t3_1_q11_q50*x115 + s_t3_1_q11_q50*x114)
    x116 = P21 + P31*c_t3_0_q11_q51
    x117 = P31*s_t3_0_q11_q51
    x118 = -x116*x68 + x117*x69
    x119 = x116*x69 + x117*x68
    x120 = (1.0 / np.sqrt(((x118) ** 2) + ((x119) ** 2)))
    s_q2_b110 = x118*x120
    c_q2_b110 = -x119*x120
    x121 = c_th14_q11_q51*x118 + s_th14_q11_q51*x119
    x122 = c_th14_q11_q51*x119 - s_th14_q11_q51*x118
    s_q4_b110 = x120*(-c_t3_0_q11_q51*x121 + s_t3_0_q11_q51*x122)
    c_q4_b110 = -x120*(c_t3_0_q11_q51*x122 + s_t3_0_q11_q51*x121)
    x123 = P21 + P31*c_t3_1_q11_q51
    x124 = P31*s_t3_1_q11_q51
    x125 = -x123*x68 + x124*x69
    x126 = x123*x69 + x124*x68
    x127 = (1.0 / np.sqrt(((x125) ** 2) + ((x126) ** 2)))
    s_q2_b111 = x125*x127
    c_q2_b111 = -x126*x127
    x128 = c_th14_q11_q51*x125 + s_th14_q11_q51*x126
    x129 = c_th14_q11_q51*x126 - s_th14_q11_q51*x125
    s_q4_b111 = x127*(-c_t3_1_q11_q51*x128 + s_t3_1_q11_q51*x129)
    c_q4_b111 = -x127*(c_t3_1_q11_q51*x129 + s_t3_1_q11_q51*x128)

    sq = np.array([
        [s_t1_0, s_t1_0, s_t1_0, s_t1_0, s_t1_1, s_t1_1, s_t1_1, s_t1_1],
        [s_q2_b000, s_q2_b001, s_q2_b010, s_q2_b011, s_q2_b100, s_q2_b101, s_q2_b110, s_q2_b111],
        [s_t3_0_q10_q50, s_t3_1_q10_q50, s_t3_0_q10_q51, s_t3_1_q10_q51, s_t3_0_q11_q50, s_t3_1_q11_q50, s_t3_0_q11_q51, s_t3_1_q11_q51],
        [s_q4_b000, s_q4_b001, s_q4_b010, s_q4_b011, s_q4_b100, s_q4_b101, s_q4_b110, s_q4_b111],
        [s_t5_0_q10, s_t5_0_q10, s_t5_1_q10, s_t5_1_q10, s_t5_0_q11, s_t5_0_q11, s_t5_1_q11, s_t5_1_q11],
        [s_q6_q10_q50, s_q6_q10_q50, s_q6_q10_q51, s_q6_q10_q51, s_q6_q11_q50, s_q6_q11_q50, s_q6_q11_q51, s_q6_q11_q51],
    ])  # (6, 8)
    cq = np.array([
        [c_t1_0, c_t1_0, c_t1_0, c_t1_0, c_t1_1, c_t1_1, c_t1_1, c_t1_1],
        [c_q2_b000, c_q2_b001, c_q2_b010, c_q2_b011, c_q2_b100, c_q2_b101, c_q2_b110, c_q2_b111],
        [c_t3_0_q10_q50, c_t3_1_q10_q50, c_t3_0_q10_q51, c_t3_1_q10_q51, c_t3_0_q11_q50, c_t3_1_q11_q50, c_t3_0_q11_q51, c_t3_1_q11_q51],
        [c_q4_b000, c_q4_b001, c_q4_b010, c_q4_b011, c_q4_b100, c_q4_b101, c_q4_b110, c_q4_b111],
        [c_t5_0_q10, c_t5_0_q10, c_t5_1_q10, c_t5_1_q10, c_t5_0_q11, c_t5_0_q11, c_t5_1_q11, c_t5_1_q11],
        [c_q6_q10_q50, c_q6_q10_q50, c_q6_q10_q51, c_q6_q10_q51, c_q6_q11_q50, c_q6_q11_q50, c_q6_q11_q51, c_q6_q11_q51],
    ])  # (6, 8)
    valid = np.empty(8, dtype=np.bool_)
    for i in range(8):
        valid[i] = not (np.any(np.isnan(sq[:, i])) or np.any(np.isnan(cq[:, i])))
    return sq, cq, valid
