# AUTO-GENERATED by jaik.kinematics.codegen — do not edit
# Robot: UR10e  |  Family: 3p2i  |  Generated: 2026-04-03
import jax.numpy as jnp
from jaxtyping import Float, Bool, Array, jaxtyped
from beartype import beartype


@jaxtyped(typechecker=beartype)
def ik_ur10e(
    R_06: Float[Array, "3 3"],
    p_0T: Float[Array, "3"],
) -> tuple[Float[Array, "6 8"], Bool[Array, "8"]]:
    """CSE-generated IK for UR10e (3p2i).
    Returns (Q, valid): Q is (6,8), valid is (8,) bool.
    NaN entries mark infeasible branches."""

    r11 = R_06[0, 0]
    r12 = R_06[0, 1]
    r13 = R_06[0, 2]
    r21 = R_06[1, 0]
    r22 = R_06[1, 1]
    r23 = R_06[1, 2]
    r31 = R_06[2, 0]
    r32 = R_06[2, 1]
    r33 = R_06[2, 2]
    p1 = p_0T[0]
    p2 = p_0T[1]
    p3 = p_0T[2]

    # ── global CSE: shared subexpressions + stage outputs ──
    x0 = 0.11655*r22
    x1 = (r12 ** 2)
    x2 = (r22 ** 2)
    x3 = jnp.sqrt(1.0*(p1 ** 2) + 0.2331*p1*r12 + 1.0*(p2 ** 2) + 0.2331*p2*r22 + 0.0135839025*x1 + 0.0135839025*x2 - 0.03032822250000001)
    x4 = x3*(1.0*p2 + x0)
    x5 = 0.17415000000000003*p1 + 0.020297182500000004*r12
    x6 = 0.11655*r12
    x7 = 1.0*p1 + x6
    x8 = 0.17415000000000003*p2 + 0.020297182500000004*r22
    t1_0 = jnp.arctan2(-x4 + x5, -x3*x7 - x8)
    t1_1 = jnp.arctan2(x4 + x5, x3*x7 - x8)
    x9 = jnp.sin(t1_0)
    x10 = jnp.cos(t1_0)
    x11 = 1.0*x1
    x12 = 1.0*x2
    x13 = 1.0*jnp.sqrt(2.0*r12*r22*x10*x9 - (x10 ** 2)*x12 - x11*(x9 ** 2) + 1.0)
    x14 = -1.0*r12*x9 + 1.0*r22*x10
    t5_0_q10 = jnp.arctan2(x13, x14)
    t5_1_q10 = jnp.arctan2(-x13, x14)
    x15 = jnp.sin(t1_1)
    x16 = jnp.cos(t1_1)
    x17 = 1.0*jnp.sqrt(2.0*r12*r22*x15*x16 - x11*(x15 ** 2) - x12*(x16 ** 2) + 1.0)
    x18 = -1.0*r12*x15 + 1.0*r22*x16
    t5_0_q11 = jnp.arctan2(x17, x18)
    t5_1_q11 = jnp.arctan2(-x17, x18)
    x19 = 1.0*jnp.sin(t5_0_q10)
    x20 = r12*x10 + r22*x9
    th14_q10_q50 = jnp.arctan2(r32*x19, x19*x20)
    x21 = r13*x9 - r23*x10
    x22 = r11*x9 - r21*x10
    q6_q10_q50 = jnp.arctan2(-x19*x21, x19*x22)
    x23 = p1 + x6
    x24 = p2 + x0
    x25 = 1.0*x9
    x26 = x10*x23 + x24*x25
    x27 = x26 - 0.11984999999999998*jnp.sin(th14_q10_q50)
    di0_q10_q50 = x27
    x28 = x10*x24 - x23*x25 + 0.17415000000000003
    di1_q10_q50 = x28
    di1_q10_q51 = x28
    x29 = 1.0*p3 + 0.11655*r32 - 0.1807
    x30 = x29 + 0.11984999999999998*jnp.cos(th14_q10_q50)
    di2_q10_q50 = x30
    x31 = (x28 ** 2)
    d3_q10_q50 = jnp.sqrt((x27 ** 2) + (x30 ** 2) + x31)
    x32 = 1.0*jnp.sin(t5_1_q10)
    th14_q10_q51 = jnp.arctan2(r32*x32, x20*x32)
    q6_q10_q51 = jnp.arctan2(-x21*x32, x22*x32)
    x33 = x26 - 0.11984999999999998*jnp.sin(th14_q10_q51)
    di0_q10_q51 = x33
    x34 = x29 + 0.11984999999999998*jnp.cos(th14_q10_q51)
    di2_q10_q51 = x34
    d3_q10_q51 = jnp.sqrt(x31 + (x33 ** 2) + (x34 ** 2))
    x35 = 1.0*jnp.sin(t5_0_q11)
    x36 = r12*x16 + r22*x15
    th14_q11_q50 = jnp.arctan2(r32*x35, x35*x36)
    x37 = r13*x15 - r23*x16
    x38 = r11*x15 - r21*x16
    q6_q11_q50 = jnp.arctan2(-x35*x37, x35*x38)
    x39 = 1.0*x15
    x40 = x16*x23 + x24*x39
    x41 = x40 - 0.11984999999999998*jnp.sin(th14_q11_q50)
    di0_q11_q50 = x41
    x42 = x16*x24 - x23*x39 + 0.17415000000000003
    di1_q11_q50 = x42
    di1_q11_q51 = x42
    x43 = x29 + 0.11984999999999998*jnp.cos(th14_q11_q50)
    di2_q11_q50 = x43
    x44 = (x42 ** 2)
    d3_q11_q50 = jnp.sqrt((x41 ** 2) + (x43 ** 2) + x44)
    x45 = 1.0*jnp.sin(t5_1_q11)
    th14_q11_q51 = jnp.arctan2(r32*x45, x36*x45)
    q6_q11_q51 = jnp.arctan2(-x37*x45, x38*x45)
    x46 = x40 - 0.11984999999999998*jnp.sin(th14_q11_q51)
    di0_q11_q51 = x46
    x47 = x29 + 0.11984999999999998*jnp.cos(th14_q11_q51)
    di2_q11_q51 = x47
    d3_q11_q51 = jnp.sqrt(x44 + (x46 ** 2) + (x47 ** 2))
    x48 = (d3_q10_q50 ** 2)
    x49 = 1.0*jnp.sqrt(-2.0386176964492657*(d3_q10_q50 ** 4) + 2.8625074757777815*x48 - 0.004841302902866884)
    x50 = 1.427801700674595*x48 - 1.0024177287452907
    t3_0_q10_q50 = jnp.arctan2(x49, x50)
    t3_1_q10_q50 = jnp.arctan2(-x49, x50)
    x51 = (d3_q10_q51 ** 2)
    x52 = 1.0*jnp.sqrt(-2.0386176964492657*(d3_q10_q51 ** 4) + 2.8625074757777815*x51 - 0.004841302902866884)
    x53 = 1.427801700674595*x51 - 1.0024177287452907
    t3_0_q10_q51 = jnp.arctan2(x52, x53)
    t3_1_q10_q51 = jnp.arctan2(-x52, x53)
    x54 = (d3_q11_q50 ** 2)
    x55 = 1.0*jnp.sqrt(-2.0386176964492657*(d3_q11_q50 ** 4) + 2.8625074757777815*x54 - 0.004841302902866884)
    x56 = 1.427801700674595*x54 - 1.0024177287452907
    t3_0_q11_q50 = jnp.arctan2(x55, x56)
    t3_1_q11_q50 = jnp.arctan2(-x55, x56)
    x57 = (d3_q11_q51 ** 2)
    x58 = 1.0*jnp.sqrt(-2.0386176964492657*(d3_q11_q51 ** 4) + 2.8625074757777815*x57 - 0.004841302902866884)
    x59 = 1.427801700674595*x57 - 1.0024177287452907
    t3_0_q11_q51 = jnp.arctan2(x58, x59)
    t3_1_q11_q51 = jnp.arctan2(-x58, x59)
    x60 = 0.57155*jnp.sin(t3_0_q10_q50)
    x61 = 0.57155*jnp.cos(t3_0_q10_q50) + 0.6127
    x62 = jnp.arctan2(di0_q10_q50*x60 - di2_q10_q50*x61, -di0_q10_q50*x61 - di2_q10_q50*x60)
    q2_b000 = x62
    x63 = -th14_q10_q50
    q4_b000 = -t3_0_q10_q50 - x62 - x63
    x64 = 0.57155*jnp.sin(t3_1_q10_q50)
    x65 = 0.57155*jnp.cos(t3_1_q10_q50) + 0.6127
    x66 = jnp.arctan2(di0_q10_q50*x64 - di2_q10_q50*x65, -di0_q10_q50*x65 - di2_q10_q50*x64)
    q2_b001 = x66
    q4_b001 = -t3_1_q10_q50 - x63 - x66
    x67 = 0.57155*jnp.sin(t3_0_q10_q51)
    x68 = 0.57155*jnp.cos(t3_0_q10_q51) + 0.6127
    x69 = jnp.arctan2(di0_q10_q51*x67 - di2_q10_q51*x68, -di0_q10_q51*x68 - di2_q10_q51*x67)
    q2_b010 = x69
    x70 = -th14_q10_q51
    q4_b010 = -t3_0_q10_q51 - x69 - x70
    x71 = 0.57155*jnp.sin(t3_1_q10_q51)
    x72 = 0.57155*jnp.cos(t3_1_q10_q51) + 0.6127
    x73 = jnp.arctan2(di0_q10_q51*x71 - di2_q10_q51*x72, -di0_q10_q51*x72 - di2_q10_q51*x71)
    q2_b011 = x73
    q4_b011 = -t3_1_q10_q51 - x70 - x73
    x74 = 0.57155*jnp.sin(t3_0_q11_q50)
    x75 = 0.57155*jnp.cos(t3_0_q11_q50) + 0.6127
    x76 = jnp.arctan2(di0_q11_q50*x74 - di2_q11_q50*x75, -di0_q11_q50*x75 - di2_q11_q50*x74)
    q2_b100 = x76
    x77 = -th14_q11_q50
    q4_b100 = -t3_0_q11_q50 - x76 - x77
    x78 = 0.57155*jnp.sin(t3_1_q11_q50)
    x79 = 0.57155*jnp.cos(t3_1_q11_q50) + 0.6127
    x80 = jnp.arctan2(di0_q11_q50*x78 - di2_q11_q50*x79, -di0_q11_q50*x79 - di2_q11_q50*x78)
    q2_b101 = x80
    q4_b101 = -t3_1_q11_q50 - x77 - x80
    x81 = 0.57155*jnp.sin(t3_0_q11_q51)
    x82 = 0.57155*jnp.cos(t3_0_q11_q51) + 0.6127
    x83 = jnp.arctan2(di0_q11_q51*x81 - di2_q11_q51*x82, -di0_q11_q51*x82 - di2_q11_q51*x81)
    q2_b110 = x83
    x84 = -th14_q11_q51
    q4_b110 = -t3_0_q11_q51 - x83 - x84
    x85 = 0.57155*jnp.sin(t3_1_q11_q51)
    x86 = 0.57155*jnp.cos(t3_1_q11_q51) + 0.6127
    x87 = jnp.arctan2(di0_q11_q51*x85 - di2_q11_q51*x86, -di0_q11_q51*x86 - di2_q11_q51*x85)
    q2_b111 = x87
    q4_b111 = -t3_1_q11_q51 - x84 - x87

    _b0 = jnp.array([t1_0, q2_b000, t3_0_q10_q50, q4_b000, t5_0_q10, q6_q10_q50])
    _b1 = jnp.array([t1_0, q2_b001, t3_1_q10_q50, q4_b001, t5_0_q10, q6_q10_q50])
    _b2 = jnp.array([t1_0, q2_b010, t3_0_q10_q51, q4_b010, t5_1_q10, q6_q10_q51])
    _b3 = jnp.array([t1_0, q2_b011, t3_1_q10_q51, q4_b011, t5_1_q10, q6_q10_q51])
    _b4 = jnp.array([t1_1, q2_b100, t3_0_q11_q50, q4_b100, t5_0_q11, q6_q11_q50])
    _b5 = jnp.array([t1_1, q2_b101, t3_1_q11_q50, q4_b101, t5_0_q11, q6_q11_q50])
    _b6 = jnp.array([t1_1, q2_b110, t3_0_q11_q51, q4_b110, t5_1_q11, q6_q11_q51])
    _b7 = jnp.array([t1_1, q2_b111, t3_1_q11_q51, q4_b111, t5_1_q11, q6_q11_q51])

    Q = jnp.stack([
        _b0,
        _b1,
        _b2,
        _b3,
        _b4,
        _b5,
        _b6,
        _b7,
    ], axis=1)  # (6, 8)

    valid = ~jnp.isnan(Q).any(axis=0)
    return Q, valid
