# AUTO-GENERATED by jaik.kinematics.codegen — do not edit
# Robot: UR10e  |  Family: 3p2i  |  Generated: 2026-04-02
import jax.numpy as jnp
from jaxtyping import Float, Bool, Array, jaxtyped
from beartype import beartype


@jaxtyped(typechecker=beartype)
def ik_ur10e(
    R_06: Float[Array, "3 3"],
    p_0T: Float[Array, "3"],
) -> tuple[Float[Array, "6 8"], Bool[Array, "8"]]:
    """CSE-generated IK for UR10e (3p2i).
    Returns (Q, valid): Q is (6,8), valid is (8,) bool.
    NaN entries mark infeasible branches."""

    r11 = R_06[0, 0]
    r12 = R_06[0, 1]
    r13 = R_06[0, 2]
    r21 = R_06[1, 0]
    r22 = R_06[1, 1]
    r23 = R_06[1, 2]
    r31 = R_06[2, 0]
    r32 = R_06[2, 1]
    r33 = R_06[2, 2]
    p1 = p_0T[0]
    p2 = p_0T[1]
    p3 = p_0T[2]

    # ── stage1_q1 ──
    _x0 = jnp.sqrt(1.0*(p1 ** 2) + 0.2331*p1*r12 + 1.0*(p2 ** 2) + 0.2331*p2*r22 + 0.0135839025*(r12 ** 2) + 0.0135839025*(r22 ** 2) - 0.03032822250000001)
    _x1 = _x0*(1.0*p2 + 0.11655*r22)
    _x2 = 0.17415000000000003*p1 + 0.020297182500000004*r12
    _x3 = 1.0*p1 + 0.11655*r12
    _x4 = 0.17415000000000003*p2 + 0.020297182500000004*r22
    t1_0 = jnp.arctan2(-_x1 + _x2, -_x0*_x3 - _x4)
    t1_1 = jnp.arctan2(_x1 + _x2, _x0*_x3 - _x4)
    # ── stage2_q5_q10 ──
    _x5 = jnp.sin(t1_0)
    _x6 = jnp.cos(t1_0)
    _x7 = 1.0*jnp.sqrt(-1.0*(_x5 ** 2)*(r12 ** 2) + 2.0*_x5*_x6*r12*r22 - 1.0*(_x6 ** 2)*(r22 ** 2) + 1.0)
    _x8 = -1.0*_x5*r12 + 1.0*_x6*r22
    t5_0_q10 = jnp.arctan2(_x7, _x8)
    t5_1_q10 = jnp.arctan2(-_x7, _x8)
    # ── stage2_q5_q11 ──
    _x9 = jnp.sin(t1_1)
    _x10 = jnp.cos(t1_1)
    _x11 = 1.0*jnp.sqrt(-1.0*(_x10 ** 2)*(r22 ** 2) + 2.0*_x10*_x9*r12*r22 - 1.0*(_x9 ** 2)*(r12 ** 2) + 1.0)
    _x12 = 1.0*_x10*r22 - 1.0*_x9*r12
    t5_0_q11 = jnp.arctan2(_x11, _x12)
    t5_1_q11 = jnp.arctan2(-_x11, _x12)
    # ── stage3a_th14q6_q10_q50 ──
    _x13 = 1.0*jnp.sin(t5_0_q10)
    _x14 = jnp.cos(t1_0)
    _x15 = jnp.sin(t1_0)
    th14_q10_q50 = jnp.arctan2(_x13*r32, _x13*(_x14*r12 + _x15*r22))
    q6_q10_q50 = jnp.arctan2(-_x13*(-_x14*r23 + _x15*r13), _x13*(-_x14*r21 + _x15*r11))
    # ── stage3b_dinner_q10_q50 ──
    _x16 = jnp.cos(t1_0)
    _x17 = p1 + 0.11655*r12
    _x18 = p2 + 0.11655*r22
    _x19 = 1.0*jnp.sin(t1_0)
    _x20 = _x16*_x17 + _x18*_x19 - 0.11984999999999998*jnp.sin(th14_q10_q50)
    _x21 = _x16*_x18 - _x17*_x19 + 0.17415000000000003
    _x22 = 1.0*p3 + 0.11655*r32 + 0.11984999999999998*jnp.cos(th14_q10_q50) - 0.1807
    di0_q10_q50 = _x20
    di1_q10_q50 = _x21
    di2_q10_q50 = _x22
    d3_q10_q50 = jnp.sqrt((_x20 ** 2) + (_x21 ** 2) + (_x22 ** 2))
    # ── stage3a_th14q6_q10_q51 ──
    _x23 = 1.0*jnp.sin(t5_1_q10)
    _x24 = jnp.cos(t1_0)
    _x25 = jnp.sin(t1_0)
    th14_q10_q51 = jnp.arctan2(_x23*r32, _x23*(_x24*r12 + _x25*r22))
    q6_q10_q51 = jnp.arctan2(-_x23*(-_x24*r23 + _x25*r13), _x23*(-_x24*r21 + _x25*r11))
    # ── stage3b_dinner_q10_q51 ──
    _x26 = jnp.cos(t1_0)
    _x27 = p1 + 0.11655*r12
    _x28 = p2 + 0.11655*r22
    _x29 = 1.0*jnp.sin(t1_0)
    _x30 = _x26*_x27 + _x28*_x29 - 0.11984999999999998*jnp.sin(th14_q10_q51)
    _x31 = _x26*_x28 - _x27*_x29 + 0.17415000000000003
    _x32 = 1.0*p3 + 0.11655*r32 + 0.11984999999999998*jnp.cos(th14_q10_q51) - 0.1807
    di0_q10_q51 = _x30
    di1_q10_q51 = _x31
    di2_q10_q51 = _x32
    d3_q10_q51 = jnp.sqrt((_x30 ** 2) + (_x31 ** 2) + (_x32 ** 2))
    # ── stage3a_th14q6_q11_q50 ──
    _x33 = 1.0*jnp.sin(t5_0_q11)
    _x34 = jnp.cos(t1_1)
    _x35 = jnp.sin(t1_1)
    th14_q11_q50 = jnp.arctan2(_x33*r32, _x33*(_x34*r12 + _x35*r22))
    q6_q11_q50 = jnp.arctan2(-_x33*(-_x34*r23 + _x35*r13), _x33*(-_x34*r21 + _x35*r11))
    # ── stage3b_dinner_q11_q50 ──
    _x36 = jnp.cos(t1_1)
    _x37 = p1 + 0.11655*r12
    _x38 = p2 + 0.11655*r22
    _x39 = 1.0*jnp.sin(t1_1)
    _x40 = _x36*_x37 + _x38*_x39 - 0.11984999999999998*jnp.sin(th14_q11_q50)
    _x41 = _x36*_x38 - _x37*_x39 + 0.17415000000000003
    _x42 = 1.0*p3 + 0.11655*r32 + 0.11984999999999998*jnp.cos(th14_q11_q50) - 0.1807
    di0_q11_q50 = _x40
    di1_q11_q50 = _x41
    di2_q11_q50 = _x42
    d3_q11_q50 = jnp.sqrt((_x40 ** 2) + (_x41 ** 2) + (_x42 ** 2))
    # ── stage3a_th14q6_q11_q51 ──
    _x43 = 1.0*jnp.sin(t5_1_q11)
    _x44 = jnp.cos(t1_1)
    _x45 = jnp.sin(t1_1)
    th14_q11_q51 = jnp.arctan2(_x43*r32, _x43*(_x44*r12 + _x45*r22))
    q6_q11_q51 = jnp.arctan2(-_x43*(-_x44*r23 + _x45*r13), _x43*(-_x44*r21 + _x45*r11))
    # ── stage3b_dinner_q11_q51 ──
    _x46 = jnp.cos(t1_1)
    _x47 = p1 + 0.11655*r12
    _x48 = p2 + 0.11655*r22
    _x49 = 1.0*jnp.sin(t1_1)
    _x50 = _x46*_x47 + _x48*_x49 - 0.11984999999999998*jnp.sin(th14_q11_q51)
    _x51 = _x46*_x48 - _x47*_x49 + 0.17415000000000003
    _x52 = 1.0*p3 + 0.11655*r32 + 0.11984999999999998*jnp.cos(th14_q11_q51) - 0.1807
    di0_q11_q51 = _x50
    di1_q11_q51 = _x51
    di2_q11_q51 = _x52
    d3_q11_q51 = jnp.sqrt((_x50 ** 2) + (_x51 ** 2) + (_x52 ** 2))
    # ── stage4_q3_q10_q50 ──
    _x53 = (d3_q10_q50 ** 2)
    _x54 = 1.0*jnp.sqrt(2.8625074757777815*_x53 - 2.0386176964492657*(d3_q10_q50 ** 4) - 0.004841302902866884)
    _x55 = 1.427801700674595*_x53 - 1.0024177287452907
    t3_0_q10_q50 = jnp.arctan2(_x54, _x55)
    t3_1_q10_q50 = jnp.arctan2(-_x54, _x55)
    # ── stage4_q3_q10_q51 ──
    _x56 = (d3_q10_q51 ** 2)
    _x57 = 1.0*jnp.sqrt(2.8625074757777815*_x56 - 2.0386176964492657*(d3_q10_q51 ** 4) - 0.004841302902866884)
    _x58 = 1.427801700674595*_x56 - 1.0024177287452907
    t3_0_q10_q51 = jnp.arctan2(_x57, _x58)
    t3_1_q10_q51 = jnp.arctan2(-_x57, _x58)
    # ── stage4_q3_q11_q50 ──
    _x59 = (d3_q11_q50 ** 2)
    _x60 = 1.0*jnp.sqrt(2.8625074757777815*_x59 - 2.0386176964492657*(d3_q11_q50 ** 4) - 0.004841302902866884)
    _x61 = 1.427801700674595*_x59 - 1.0024177287452907
    t3_0_q11_q50 = jnp.arctan2(_x60, _x61)
    t3_1_q11_q50 = jnp.arctan2(-_x60, _x61)
    # ── stage4_q3_q11_q51 ──
    _x62 = (d3_q11_q51 ** 2)
    _x63 = 1.0*jnp.sqrt(2.8625074757777815*_x62 - 2.0386176964492657*(d3_q11_q51 ** 4) - 0.004841302902866884)
    _x64 = 1.427801700674595*_x62 - 1.0024177287452907
    t3_0_q11_q51 = jnp.arctan2(_x63, _x64)
    t3_1_q11_q51 = jnp.arctan2(-_x63, _x64)
    # ── stage5_q2q4_q10_q50_q30 ──
    _x65 = 0.57155*jnp.sin(t3_0_q10_q50)
    _x66 = 0.57155*jnp.cos(t3_0_q10_q50) + 0.6127
    _x67 = jnp.arctan2(_x65*di0_q10_q50 - _x66*di2_q10_q50, -_x65*di2_q10_q50 - _x66*di0_q10_q50)
    q2_stage5_q2q4_q10_q50_q30 = _x67
    q4_stage5_q2q4_q10_q50_q30 = -_x67 - t3_0_q10_q50 + th14_q10_q50
    # ── stage5_q2q4_q10_q50_q31 ──
    _x68 = 0.57155*jnp.sin(t3_1_q10_q50)
    _x69 = 0.57155*jnp.cos(t3_1_q10_q50) + 0.6127
    _x70 = jnp.arctan2(_x68*di0_q10_q50 - _x69*di2_q10_q50, -_x68*di2_q10_q50 - _x69*di0_q10_q50)
    q2_stage5_q2q4_q10_q50_q31 = _x70
    q4_stage5_q2q4_q10_q50_q31 = -_x70 - t3_1_q10_q50 + th14_q10_q50
    # ── stage5_q2q4_q10_q51_q30 ──
    _x71 = 0.57155*jnp.sin(t3_0_q10_q51)
    _x72 = 0.57155*jnp.cos(t3_0_q10_q51) + 0.6127
    _x73 = jnp.arctan2(_x71*di0_q10_q51 - _x72*di2_q10_q51, -_x71*di2_q10_q51 - _x72*di0_q10_q51)
    q2_stage5_q2q4_q10_q51_q30 = _x73
    q4_stage5_q2q4_q10_q51_q30 = -_x73 - t3_0_q10_q51 + th14_q10_q51
    # ── stage5_q2q4_q10_q51_q31 ──
    _x74 = 0.57155*jnp.sin(t3_1_q10_q51)
    _x75 = 0.57155*jnp.cos(t3_1_q10_q51) + 0.6127
    _x76 = jnp.arctan2(_x74*di0_q10_q51 - _x75*di2_q10_q51, -_x74*di2_q10_q51 - _x75*di0_q10_q51)
    q2_stage5_q2q4_q10_q51_q31 = _x76
    q4_stage5_q2q4_q10_q51_q31 = -_x76 - t3_1_q10_q51 + th14_q10_q51
    # ── stage5_q2q4_q11_q50_q30 ──
    _x77 = 0.57155*jnp.sin(t3_0_q11_q50)
    _x78 = 0.57155*jnp.cos(t3_0_q11_q50) + 0.6127
    _x79 = jnp.arctan2(_x77*di0_q11_q50 - _x78*di2_q11_q50, -_x77*di2_q11_q50 - _x78*di0_q11_q50)
    q2_stage5_q2q4_q11_q50_q30 = _x79
    q4_stage5_q2q4_q11_q50_q30 = -_x79 - t3_0_q11_q50 + th14_q11_q50
    # ── stage5_q2q4_q11_q50_q31 ──
    _x80 = 0.57155*jnp.sin(t3_1_q11_q50)
    _x81 = 0.57155*jnp.cos(t3_1_q11_q50) + 0.6127
    _x82 = jnp.arctan2(_x80*di0_q11_q50 - _x81*di2_q11_q50, -_x80*di2_q11_q50 - _x81*di0_q11_q50)
    q2_stage5_q2q4_q11_q50_q31 = _x82
    q4_stage5_q2q4_q11_q50_q31 = -_x82 - t3_1_q11_q50 + th14_q11_q50
    # ── stage5_q2q4_q11_q51_q30 ──
    _x83 = 0.57155*jnp.sin(t3_0_q11_q51)
    _x84 = 0.57155*jnp.cos(t3_0_q11_q51) + 0.6127
    _x85 = jnp.arctan2(_x83*di0_q11_q51 - _x84*di2_q11_q51, -_x83*di2_q11_q51 - _x84*di0_q11_q51)
    q2_stage5_q2q4_q11_q51_q30 = _x85
    q4_stage5_q2q4_q11_q51_q30 = -_x85 - t3_0_q11_q51 + th14_q11_q51
    # ── stage5_q2q4_q11_q51_q31 ──
    _x86 = 0.57155*jnp.sin(t3_1_q11_q51)
    _x87 = 0.57155*jnp.cos(t3_1_q11_q51) + 0.6127
    _x88 = jnp.arctan2(_x86*di0_q11_q51 - _x87*di2_q11_q51, -_x86*di2_q11_q51 - _x87*di0_q11_q51)
    q2_stage5_q2q4_q11_q51_q31 = _x88
    q4_stage5_q2q4_q11_q51_q31 = -_x88 - t3_1_q11_q51 + th14_q11_q51
    _b0 = jnp.array([t1_0, q2_stage5_q2q4_q10_q50_q30, t3_0_q10_q50, q4_stage5_q2q4_q10_q50_q30, t5_0_q10, q6_q10_q50])
    _b1 = jnp.array([t1_0, q2_stage5_q2q4_q10_q50_q31, t3_1_q10_q50, q4_stage5_q2q4_q10_q50_q31, t5_0_q10, q6_q10_q50])
    _b2 = jnp.array([t1_0, q2_stage5_q2q4_q10_q51_q30, t3_0_q10_q51, q4_stage5_q2q4_q10_q51_q30, t5_1_q10, q6_q10_q51])
    _b3 = jnp.array([t1_0, q2_stage5_q2q4_q10_q51_q31, t3_1_q10_q51, q4_stage5_q2q4_q10_q51_q31, t5_1_q10, q6_q10_q51])
    _b4 = jnp.array([t1_1, q2_stage5_q2q4_q11_q50_q30, t3_0_q11_q50, q4_stage5_q2q4_q11_q50_q30, t5_0_q11, q6_q11_q50])
    _b5 = jnp.array([t1_1, q2_stage5_q2q4_q11_q50_q31, t3_1_q11_q50, q4_stage5_q2q4_q11_q50_q31, t5_0_q11, q6_q11_q50])
    _b6 = jnp.array([t1_1, q2_stage5_q2q4_q11_q51_q30, t3_0_q11_q51, q4_stage5_q2q4_q11_q51_q30, t5_1_q11, q6_q11_q51])
    _b7 = jnp.array([t1_1, q2_stage5_q2q4_q11_q51_q31, t3_1_q11_q51, q4_stage5_q2q4_q11_q51_q31, t5_1_q11, q6_q11_q51])

    Q = jnp.stack([
        _b0,
        _b1,
        _b2,
        _b3,
        _b4,
        _b5,
        _b6,
        _b7,
    ], axis=1)  # (6, 8)

    valid = ~jnp.isnan(Q).any(axis=0)
    return Q, valid
