# AUTO-GENERATED by jaik.kinematics.codegen — do not edit
# Robot: ur10e  |  Generated: 2026-04-06
import jax.numpy as jnp
from jaxtyping import Float, Bool, Array, jaxtyped
from beartype import beartype


@jaxtyped(typechecker=beartype)
def fk(sq, cq):
    P03 = 0.1807
    P21 = -0.6127
    P31 = -0.57155
    P42 = -0.17415000000000003
    P43 = -0.11984999999999998
    P62 = -0.11655


    sq1 = sq[0]
    sq2 = sq[1]
    sq3 = sq[2]
    sq4 = sq[3]
    sq5 = sq[4]
    sq6 = sq[5]
    cq1 = cq[0]
    cq2 = cq[1]
    cq3 = cq[2]
    cq4 = cq[3]
    cq5 = cq[4]
    cq6 = cq[5]

    # ── global CSE: shared subexpressions + stage outputs ──
    x0 = cq2*sq3 + cq3*sq2
    x1 = cq2*cq3 - sq2*sq3
    x2 = cq4*x0 + sq4*x1
    x3 = cq1*x2
    x4 = sq1*sq5
    x5 = cq4*x1 - sq4*x0
    x6 = cq1*cq5
    x7 = x4 + x5*x6
    x8 = cq5*sq1
    x9 = cq1*sq5
    x10 = x5*x9 - x8
    x11 = sq1*x2
    x12 = -x5*x8 + x9
    x13 = x4*x5 + x6
    x14 = cq5*x2
    x15 = sq5*x2
    x16 = P21*cq2
    x17 = P31*x1
    r11 = cq6*x7 - sq6*x3
    r12 = x10
    r13 = -cq6*x3 - sq6*x7
    r21 = -cq6*x12 - sq6*x11
    r22 = x13
    r23 = -cq6*x11 + sq6*x12
    r31 = cq6*x14 + sq6*x5
    r32 = x15
    r33 = cq6*x5 - sq6*x14
    p1 = -P42*sq1 - P43*x3 + P62*x10 + cq1*x16 + cq1*x17
    p2 = P42*cq1 - P43*x11 + P62*x13 + sq1*x16 + sq1*x17
    p3 = P03 + P21*sq2 + P31*x0 + P43*x5 + P62*x15

    # ── aliases ──

    R = jnp.array([
        [r11, r12, r13],
        [r21, r22, r23],
        [r31, r32, r33],
    ])  # (3, 3)
    p = jnp.array([p1, p2, p3])  # (3,)
    return R, p

@jaxtyped(typechecker=beartype)
def ik_full(
    R_06: Float[Array, "3 3"],
    p_0T: Float[Array, "3"],
) -> tuple[Float[Array, "6 8"], Float[Array, "6 8"], Bool[Array, "8"]]:
    """CSE-generated IK for ur10e.
    Returns (sinQ, cosQ, valid): sinQ, cosQ are (6,8), valid is (8,) bool.
    NaN entries mark infeasible branches."""

    P03 = 0.1807
    P21 = -0.6127
    P31 = -0.57155
    P42 = -0.17415000000000003
    P43 = -0.11984999999999998
    P62 = -0.11655

    c0 = -((P42) ** 2)
    c1 = ((P62) ** 2)
    c2 = ((P21) ** 2)
    c3 = ((P31) ** 2)
    c4 = ((P21) ** 4) + ((P31) ** 4) - 2*c2*c3
    c5 = (0.5)/(P21*P31)
    c6 = -c2 - c3

    r11 = R_06[0, 0]
    r12 = R_06[0, 1]
    r13 = R_06[0, 2]
    r21 = R_06[1, 0]
    r22 = R_06[1, 1]
    r23 = R_06[1, 2]
    r31 = R_06[2, 0]
    r32 = R_06[2, 1]
    r33 = R_06[2, 2]
    p1 = p_0T[0]
    p2 = p_0T[1]
    p3 = p_0T[2]

    # ── global CSE: shared subexpressions + stage outputs ──
    x0 = P62*r12
    x1 = -p1 + x0
    x2 = P42*x1
    x3 = P62*r22
    x4 = -p2 + x3
    x5 = ((r12) ** 2)
    x6 = ((r22) ** 2)
    x7 = jnp.sqrt(c0 + c1*x5 + c1*x6 + ((p1) ** 2) - 2*p1*x0 + ((p2) ** 2) - 2*p2*x3)
    x8 = x4*x7
    x9 = x2 + x8
    x10 = P42*x4
    x11 = x1*x7
    x12 = x10 - x11
    x13 = (1.0 / (jnp.hypot(x12, x9)))
    x14 = x2 - x8
    x15 = x10 + x11
    x16 = (1.0 / (jnp.hypot(x14, x15)))
    s_t1_0 = x13*x9
    c_t1_0 = -x12*x13
    x17 = c_t1_0*r12 + r22*s_t1_0
    s_t5_0_q10 = jnp.sqrt(-((c_t1_0) ** 2)*x6 + 2*c_t1_0*r12*r22*s_t1_0 - ((s_t1_0) ** 2)*x5 + 1)
    x18 = jnp.sign(s_t5_0_q10)
    x19 = x18/jnp.hypot(r32, x17)
    x20 = r32*x19
    x21 = x17*x19
    x22 = c_t1_0*r23 - r13*s_t1_0
    x23 = c_t1_0*r21 - r11*s_t1_0
    x24 = x18/jnp.hypot(x23, x22)
    x25 = x22*x24
    x26 = x23*x24
    x27 = -c4
    x28 = P03 + P62*r32 - p3
    c_th14_q10_q50 = x21
    x29 = P43*c_th14_q10_q50 + x28
    x30 = ((P42 + c_t1_0*x4 - s_t1_0*x1) ** 2)
    x31 = c_t1_0*x1 + s_t1_0*x4
    s_th14_q10_q50 = x20
    x32 = -P43*s_th14_q10_q50 + x31
    x33 = ((x29) ** 2) + x30 + ((x32) ** 2)
    x34 = 2*x33
    c_th14_q10_q51 = -x21
    x35 = P43*c_th14_q10_q51 + x28
    s_th14_q10_q51 = -x20
    x36 = -P43*s_th14_q10_q51 + x31
    x37 = x30 + ((x35) ** 2) + ((x36) ** 2)
    x38 = 2*x37
    s_t1_1 = x14*x16
    c_t1_1 = -x15*x16
    x39 = c_t1_1*r12 + r22*s_t1_1
    s_t5_0_q11 = jnp.sqrt(-((c_t1_1) ** 2)*x6 + 2*c_t1_1*r12*r22*s_t1_1 - ((s_t1_1) ** 2)*x5 + 1)
    x40 = jnp.sign(s_t5_0_q11)
    x41 = x40/jnp.hypot(r32, x39)
    x42 = r32*x41
    x43 = x39*x41
    x44 = c_t1_1*r23 - r13*s_t1_1
    x45 = c_t1_1*r21 - r11*s_t1_1
    x46 = x40/jnp.hypot(x45, x44)
    x47 = x44*x46
    x48 = x45*x46
    c_th14_q11_q50 = x43
    x49 = P43*c_th14_q11_q50 + x28
    x50 = ((P42 + c_t1_1*x4 - s_t1_1*x1) ** 2)
    x51 = c_t1_1*x1 + s_t1_1*x4
    s_th14_q11_q50 = x42
    x52 = -P43*s_th14_q11_q50 + x51
    x53 = ((x49) ** 2) + x50 + ((x52) ** 2)
    x54 = 2*x53
    c_th14_q11_q51 = -x43
    x55 = P43*c_th14_q11_q51 + x28
    s_th14_q11_q51 = -x42
    x56 = -P43*s_th14_q11_q51 + x51
    x57 = x50 + ((x55) ** 2) + ((x56) ** 2)
    x58 = 2*x57
    c_t3_0_q10_q50 = c5*(c6 + x33)
    x59 = P21 + P31*c_t3_0_q10_q50
    x60 = x29*x59
    s_t3_0_q10_q50 = c5*jnp.sqrt(c2*x34 + c3*x34 + x27 - ((x33) ** 2))
    x61 = P31*s_t3_0_q10_q50
    x62 = x32*x61
    x63 = -x60 + x62
    x64 = x29*x61
    x65 = x32*x59
    x66 = x64 + x65
    x67 = (1.0 / (jnp.hypot(x66, x63)))
    x68 = c_th14_q10_q50*x63 + s_th14_q10_q50*x66
    x69 = c_th14_q10_q50*x66 - s_th14_q10_q50*x63
    x70 = x60 + x62
    x71 = x64 - x65
    x72 = (1.0 / (jnp.hypot(x70, x71)))
    x73 = c_th14_q10_q50*x70 + s_th14_q10_q50*x71
    x74 = c_th14_q10_q50*x71 - s_th14_q10_q50*x70
    c_t3_0_q10_q51 = c5*(c6 + x37)
    x75 = P21 + P31*c_t3_0_q10_q51
    x76 = x35*x75
    s_t3_0_q10_q51 = c5*jnp.sqrt(c2*x38 + c3*x38 + x27 - ((x37) ** 2))
    x77 = P31*s_t3_0_q10_q51
    x78 = x36*x77
    x79 = -x76 + x78
    x80 = x35*x77
    x81 = x36*x75
    x82 = x80 + x81
    x83 = (1.0 / (jnp.hypot(x82, x79)))
    x84 = c_th14_q10_q51*x79 + s_th14_q10_q51*x82
    x85 = c_th14_q10_q51*x82 - s_th14_q10_q51*x79
    x86 = x76 + x78
    x87 = x80 - x81
    x88 = (1.0 / (jnp.hypot(x86, x87)))
    x89 = c_th14_q10_q51*x86 + s_th14_q10_q51*x87
    x90 = c_th14_q10_q51*x87 - s_th14_q10_q51*x86
    c_t3_0_q11_q50 = c5*(c6 + x53)
    x91 = P21 + P31*c_t3_0_q11_q50
    x92 = x49*x91
    s_t3_0_q11_q50 = c5*jnp.sqrt(c2*x54 + c3*x54 + x27 - ((x53) ** 2))
    x93 = P31*s_t3_0_q11_q50
    x94 = x52*x93
    x95 = -x92 + x94
    x96 = x49*x93
    x97 = x52*x91
    x98 = x96 + x97
    x99 = (1.0 / (jnp.hypot(x98, x95)))
    x100 = c_th14_q11_q50*x95 + s_th14_q11_q50*x98
    x101 = c_th14_q11_q50*x98 - s_th14_q11_q50*x95
    x102 = x92 + x94
    x103 = x96 - x97
    x104 = (1.0 / (jnp.hypot(x102, x103)))
    x105 = c_th14_q11_q50*x102 + s_th14_q11_q50*x103
    x106 = c_th14_q11_q50*x103 - s_th14_q11_q50*x102
    c_t3_0_q11_q51 = c5*(c6 + x57)
    x107 = P21 + P31*c_t3_0_q11_q51
    x108 = x107*x55
    s_t3_0_q11_q51 = c5*jnp.sqrt(c2*x58 + c3*x58 + x27 - ((x57) ** 2))
    x109 = P31*s_t3_0_q11_q51
    x110 = x109*x56
    x111 = -x108 + x110
    x112 = x109*x55
    x113 = x107*x56
    x114 = x112 + x113
    x115 = (1.0 / (jnp.hypot(x114, x111)))
    x116 = c_th14_q11_q51*x111 + s_th14_q11_q51*x114
    x117 = c_th14_q11_q51*x114 - s_th14_q11_q51*x111
    x118 = x108 + x110
    x119 = x112 - x113
    x120 = (1.0 / (jnp.hypot(x118, x119)))
    x121 = c_th14_q11_q51*x118 + s_th14_q11_q51*x119
    x122 = c_th14_q11_q51*x119 - s_th14_q11_q51*x118
    c_t5_0_q10 = c_t1_0*r22 - r12*s_t1_0
    s_q6_q10_q50 = x25
    c_q6_q10_q50 = -x26
    s_q6_q10_q51 = -x25
    c_q6_q10_q51 = x26
    c_t5_0_q11 = c_t1_1*r22 - r12*s_t1_1
    s_q6_q11_q50 = x47
    c_q6_q11_q50 = -x48
    s_q6_q11_q51 = -x47
    c_q6_q11_q51 = x48
    s_q2_b000 = x63*x67
    c_q2_b000 = -x66*x67
    s_q4_b000 = -x67*(c_t3_0_q10_q50*x68 - s_t3_0_q10_q50*x69)
    c_q4_b000 = -x67*(c_t3_0_q10_q50*x69 + s_t3_0_q10_q50*x68)
    s_q2_b001 = -x70*x72
    c_q2_b001 = x71*x72
    s_q4_b001 = x72*(c_t3_0_q10_q50*x73 + s_t3_0_q10_q50*x74)
    c_q4_b001 = x72*(c_t3_0_q10_q50*x74 - s_t3_0_q10_q50*x73)
    s_q2_b010 = x79*x83
    c_q2_b010 = -x82*x83
    s_q4_b010 = -x83*(c_t3_0_q10_q51*x84 - s_t3_0_q10_q51*x85)
    c_q4_b010 = -x83*(c_t3_0_q10_q51*x85 + s_t3_0_q10_q51*x84)
    s_q2_b011 = -x86*x88
    c_q2_b011 = x87*x88
    s_q4_b011 = x88*(c_t3_0_q10_q51*x89 + s_t3_0_q10_q51*x90)
    c_q4_b011 = x88*(c_t3_0_q10_q51*x90 - s_t3_0_q10_q51*x89)
    s_q2_b100 = x95*x99
    c_q2_b100 = -x98*x99
    s_q4_b100 = -x99*(c_t3_0_q11_q50*x100 - s_t3_0_q11_q50*x101)
    c_q4_b100 = -x99*(c_t3_0_q11_q50*x101 + s_t3_0_q11_q50*x100)
    s_q2_b101 = -x102*x104
    c_q2_b101 = x103*x104
    s_q4_b101 = x104*(c_t3_0_q11_q50*x105 + s_t3_0_q11_q50*x106)
    c_q4_b101 = x104*(c_t3_0_q11_q50*x106 - s_t3_0_q11_q50*x105)
    s_q2_b110 = x111*x115
    c_q2_b110 = -x114*x115
    s_q4_b110 = -x115*(c_t3_0_q11_q51*x116 - s_t3_0_q11_q51*x117)
    c_q4_b110 = -x115*(c_t3_0_q11_q51*x117 + s_t3_0_q11_q51*x116)
    s_q2_b111 = -x118*x120
    c_q2_b111 = x119*x120
    s_q4_b111 = x120*(c_t3_0_q11_q51*x121 + s_t3_0_q11_q51*x122)
    c_q4_b111 = x120*(c_t3_0_q11_q51*x122 - s_t3_0_q11_q51*x121)

    # ── aliases ──
    s_t5_1_q10 = -s_t5_0_q10
    c_t5_1_q10 = c_t5_0_q10
    s_t3_1_q10_q50 = -s_t3_0_q10_q50
    c_t3_1_q10_q50 = c_t3_0_q10_q50
    s_t3_1_q10_q51 = -s_t3_0_q10_q51
    c_t3_1_q10_q51 = c_t3_0_q10_q51
    s_t5_1_q11 = -s_t5_0_q11
    c_t5_1_q11 = c_t5_0_q11
    s_t3_1_q11_q50 = -s_t3_0_q11_q50
    c_t3_1_q11_q50 = c_t3_0_q11_q50
    s_t3_1_q11_q51 = -s_t3_0_q11_q51
    c_t3_1_q11_q51 = c_t3_0_q11_q51

    sq = jnp.array([
        [s_t1_0, s_t1_0, s_t1_0, s_t1_0, s_t1_1, s_t1_1, s_t1_1, s_t1_1],
        [s_q2_b000, s_q2_b001, s_q2_b010, s_q2_b011, s_q2_b100, s_q2_b101, s_q2_b110, s_q2_b111],
        [s_t3_0_q10_q50, s_t3_1_q10_q50, s_t3_0_q10_q51, s_t3_1_q10_q51, s_t3_0_q11_q50, s_t3_1_q11_q50, s_t3_0_q11_q51, s_t3_1_q11_q51],
        [s_q4_b000, s_q4_b001, s_q4_b010, s_q4_b011, s_q4_b100, s_q4_b101, s_q4_b110, s_q4_b111],
        [s_t5_0_q10, s_t5_0_q10, s_t5_1_q10, s_t5_1_q10, s_t5_0_q11, s_t5_0_q11, s_t5_1_q11, s_t5_1_q11],
        [s_q6_q10_q50, s_q6_q10_q50, s_q6_q10_q51, s_q6_q10_q51, s_q6_q11_q50, s_q6_q11_q50, s_q6_q11_q51, s_q6_q11_q51],
    ])  # (6, 8)
    cq = jnp.array([
        [c_t1_0, c_t1_0, c_t1_0, c_t1_0, c_t1_1, c_t1_1, c_t1_1, c_t1_1],
        [c_q2_b000, c_q2_b001, c_q2_b010, c_q2_b011, c_q2_b100, c_q2_b101, c_q2_b110, c_q2_b111],
        [c_t3_0_q10_q50, c_t3_1_q10_q50, c_t3_0_q10_q51, c_t3_1_q10_q51, c_t3_0_q11_q50, c_t3_1_q11_q50, c_t3_0_q11_q51, c_t3_1_q11_q51],
        [c_q4_b000, c_q4_b001, c_q4_b010, c_q4_b011, c_q4_b100, c_q4_b101, c_q4_b110, c_q4_b111],
        [c_t5_0_q10, c_t5_0_q10, c_t5_1_q10, c_t5_1_q10, c_t5_0_q11, c_t5_0_q11, c_t5_1_q11, c_t5_1_q11],
        [c_q6_q10_q50, c_q6_q10_q50, c_q6_q10_q51, c_q6_q10_q51, c_q6_q11_q50, c_q6_q11_q50, c_q6_q11_q51, c_q6_q11_q51],
    ])  # (6, 8)
    valid = ~(jnp.isnan(sq) | jnp.isnan(cq)).any(axis=0)
    return sq, cq, valid
