# AUTO-GENERATED by jaik.kinematics.codegen — do not edit
# Robot: ur3  |  Generated: 2026-04-06
import jax.numpy as jnp
from jaxtyping import Float, Bool, Array, jaxtyped
from beartype import beartype


@jaxtyped(typechecker=beartype)
def fk(sq, cq):
    P03 = 0.1519
    P21 = -0.24365
    P31 = -0.21325
    P42 = -0.11235000000000002
    P43 = -0.08534999999999998
    P62 = -0.0819


    sq1 = sq[0]
    sq2 = sq[1]
    sq3 = sq[2]
    sq4 = sq[3]
    sq5 = sq[4]
    sq6 = sq[5]
    cq1 = cq[0]
    cq2 = cq[1]
    cq3 = cq[2]
    cq4 = cq[3]
    cq5 = cq[4]
    cq6 = cq[5]

    # ── global CSE: shared subexpressions + stage outputs ──
    x0 = cq2*sq3 + cq3*sq2
    x1 = cq2*cq3 - sq2*sq3
    x2 = cq4*x0 + sq4*x1
    x3 = cq1*x2
    x4 = sq1*sq5
    x5 = cq4*x1 - sq4*x0
    x6 = cq1*cq5
    x7 = x4 + x5*x6
    x8 = cq5*sq1
    x9 = cq1*sq5
    x10 = x5*x9 - x8
    x11 = sq1*x2
    x12 = -x5*x8 + x9
    x13 = x4*x5 + x6
    x14 = cq5*x2
    x15 = sq5*x2
    x16 = P21*cq2
    x17 = P31*x1
    r11 = cq6*x7 - sq6*x3
    r12 = x10
    r13 = -cq6*x3 - sq6*x7
    r21 = -cq6*x12 - sq6*x11
    r22 = x13
    r23 = -cq6*x11 + sq6*x12
    r31 = cq6*x14 + sq6*x5
    r32 = x15
    r33 = cq6*x5 - sq6*x14
    p1 = -P42*sq1 - P43*x3 + P62*x10 + cq1*x16 + cq1*x17
    p2 = P42*cq1 - P43*x11 + P62*x13 + sq1*x16 + sq1*x17
    p3 = P03 + P21*sq2 + P31*x0 + P43*x5 + P62*x15

    # ── aliases ──

    R = jnp.array([
        [r11, r12, r13],
        [r21, r22, r23],
        [r31, r32, r33],
    ])  # (3, 3)
    p = jnp.array([p1, p2, p3])  # (3,)
    return R, p

@jaxtyped(typechecker=beartype)
def ik_full(
    R_06: Float[Array, "3 3"],
    p_0T: Float[Array, "3"],
) -> tuple[Float[Array, "6 8"], Float[Array, "6 8"], Bool[Array, "8"]]:
    """CSE-generated IK for ur3.
    Returns (sinQ, cosQ, valid): sinQ, cosQ are (6,8), valid is (8,) bool.
    NaN entries mark infeasible branches."""

    P03 = 0.1519
    P21 = -0.24365
    P31 = -0.21325
    P42 = -0.11235000000000002
    P43 = -0.08534999999999998
    P62 = -0.0819

    c0 = -((P42) ** 2)
    c1 = ((P62) ** 2)
    c2 = ((P21) ** 2)
    c3 = ((P31) ** 2)
    c4 = ((P21) ** 4) + ((P31) ** 4) - 2*c2*c3
    c5 = (0.5)/(P21*P31)
    c6 = -c2 - c3

    r11 = R_06[0, 0]
    r12 = R_06[0, 1]
    r13 = R_06[0, 2]
    r21 = R_06[1, 0]
    r22 = R_06[1, 1]
    r23 = R_06[1, 2]
    r31 = R_06[2, 0]
    r32 = R_06[2, 1]
    r33 = R_06[2, 2]
    p1 = p_0T[0]
    p2 = p_0T[1]
    p3 = p_0T[2]

    # ── global CSE: shared subexpressions + stage outputs ──
    x0 = P62*r12
    x1 = -p1 + x0
    x2 = P42*x1
    x3 = P62*r22
    x4 = -p2 + x3
    x5 = ((r12) ** 2)
    x6 = ((r22) ** 2)
    x7 = jnp.sqrt(c0 + c1*x5 + c1*x6 + ((p1) ** 2) - 2*p1*x0 + ((p2) ** 2) - 2*p2*x3)
    x8 = x4*x7
    x9 = x2 + x8
    x10 = P42*x4
    x11 = x1*x7
    x12 = x10 - x11
    x13 = (1.0 / (jnp.hypot(x12, x9)))
    x14 = x2 - x8
    x15 = x10 + x11
    x16 = (1.0 / (jnp.hypot(x14, x15)))
    s_t1_0 = x13*x9
    c_t1_0 = -x12*x13
    x17 = jnp.sqrt(-((c_t1_0) ** 2)*x6 + 2*c_t1_0*r12*r22*s_t1_0 - ((s_t1_0) ** 2)*x5 + 1)
    s_t5_0_q10 = x17
    x18 = jnp.sign(s_t5_0_q10)
    x19 = c_t1_0*r12 + r22*s_t1_0
    x20 = (1.0 / (jnp.hypot(r32, x19)))
    x21 = r32*x20
    x22 = x19*x20
    x23 = c_t1_0*r23 - r13*s_t1_0
    x24 = c_t1_0*r21 - r11*s_t1_0
    x25 = (1.0 / (jnp.hypot(x24, x23)))
    x26 = x18*x25
    x27 = -c4
    x28 = P03 + P62*r32 - p3
    c_th14_q10_q50 = x18*x22
    x29 = P43*c_th14_q10_q50 + x28
    x30 = ((P42 + c_t1_0*x4 - s_t1_0*x1) ** 2)
    x31 = c_t1_0*x1 + s_t1_0*x4
    s_th14_q10_q50 = x18*x21
    x32 = -P43*s_th14_q10_q50 + x31
    x33 = ((x29) ** 2) + x30 + ((x32) ** 2)
    x34 = 2*x33
    x35 = c5*jnp.sqrt(c2*x34 + c3*x34 + x27 - ((x33) ** 2))
    s_t5_1_q10 = -x17
    x36 = jnp.sign(s_t5_1_q10)
    x37 = x25*x36
    c_th14_q10_q51 = x22*x36
    x38 = P43*c_th14_q10_q51 + x28
    s_th14_q10_q51 = x21*x36
    x39 = -P43*s_th14_q10_q51 + x31
    x40 = x30 + ((x38) ** 2) + ((x39) ** 2)
    x41 = 2*x40
    x42 = c5*jnp.sqrt(c2*x41 + c3*x41 + x27 - ((x40) ** 2))
    c_t1_1 = -x15*x16
    s_t1_1 = x14*x16
    x43 = jnp.sqrt(-((c_t1_1) ** 2)*x6 + 2*c_t1_1*r12*r22*s_t1_1 - ((s_t1_1) ** 2)*x5 + 1)
    s_t5_0_q11 = x43
    x44 = jnp.sign(s_t5_0_q11)
    x45 = c_t1_1*r12 + r22*s_t1_1
    x46 = (1.0 / (jnp.hypot(r32, x45)))
    x47 = r32*x46
    x48 = x45*x46
    x49 = c_t1_1*r23 - r13*s_t1_1
    x50 = c_t1_1*r21 - r11*s_t1_1
    x51 = (1.0 / (jnp.hypot(x50, x49)))
    x52 = x44*x51
    c_th14_q11_q50 = x44*x48
    x53 = P43*c_th14_q11_q50 + x28
    x54 = ((P42 + c_t1_1*x4 - s_t1_1*x1) ** 2)
    x55 = c_t1_1*x1 + s_t1_1*x4
    s_th14_q11_q50 = x44*x47
    x56 = -P43*s_th14_q11_q50 + x55
    x57 = ((x53) ** 2) + x54 + ((x56) ** 2)
    x58 = 2*x57
    x59 = c5*jnp.sqrt(c2*x58 + c3*x58 + x27 - ((x57) ** 2))
    s_t5_1_q11 = -x43
    x60 = jnp.sign(s_t5_1_q11)
    x61 = x51*x60
    c_th14_q11_q51 = x48*x60
    x62 = P43*c_th14_q11_q51 + x28
    s_th14_q11_q51 = x47*x60
    x63 = -P43*s_th14_q11_q51 + x55
    x64 = x54 + ((x62) ** 2) + ((x63) ** 2)
    x65 = 2*x64
    x66 = c5*jnp.sqrt(c2*x65 + c3*x65 + x27 - ((x64) ** 2))
    c_t3_0_q10_q50 = c5*(c6 + x33)
    x67 = P21 + P31*c_t3_0_q10_q50
    s_t3_0_q10_q50 = x35
    x68 = P31*s_t3_0_q10_q50
    x69 = -x29*x67 + x32*x68
    x70 = x29*x68 + x32*x67
    x71 = (1.0 / (jnp.hypot(-x69, x70)))
    x72 = c_th14_q10_q50*x69 + s_th14_q10_q50*x70
    x73 = c_th14_q10_q50*x70 - s_th14_q10_q50*x69
    x74 = P21 + P31*c_t3_0_q10_q50
    s_t3_1_q10_q50 = -x35
    x75 = P31*s_t3_1_q10_q50
    x76 = -x29*x74 + x32*x75
    x77 = x29*x75 + x32*x74
    x78 = (1.0 / (jnp.hypot(-x76, x77)))
    x79 = c_th14_q10_q50*x76 + s_th14_q10_q50*x77
    x80 = c_th14_q10_q50*x77 - s_th14_q10_q50*x76
    c_t3_0_q10_q51 = c5*(c6 + x40)
    x81 = P21 + P31*c_t3_0_q10_q51
    s_t3_0_q10_q51 = x42
    x82 = P31*s_t3_0_q10_q51
    x83 = -x38*x81 + x39*x82
    x84 = x38*x82 + x39*x81
    x85 = (1.0 / (jnp.hypot(-x83, x84)))
    x86 = c_th14_q10_q51*x83 + s_th14_q10_q51*x84
    x87 = c_th14_q10_q51*x84 - s_th14_q10_q51*x83
    x88 = P21 + P31*c_t3_0_q10_q51
    s_t3_1_q10_q51 = -x42
    x89 = P31*s_t3_1_q10_q51
    x90 = -x38*x88 + x39*x89
    x91 = x38*x89 + x39*x88
    x92 = (1.0 / (jnp.hypot(-x90, x91)))
    x93 = c_th14_q10_q51*x90 + s_th14_q10_q51*x91
    x94 = c_th14_q10_q51*x91 - s_th14_q10_q51*x90
    c_t3_0_q11_q50 = c5*(c6 + x57)
    x95 = P21 + P31*c_t3_0_q11_q50
    s_t3_0_q11_q50 = x59
    x96 = P31*s_t3_0_q11_q50
    x97 = -x53*x95 + x56*x96
    x98 = x53*x96 + x56*x95
    x99 = (1.0 / (jnp.hypot(-x97, x98)))
    x100 = c_th14_q11_q50*x97 + s_th14_q11_q50*x98
    x101 = c_th14_q11_q50*x98 - s_th14_q11_q50*x97
    x102 = P21 + P31*c_t3_0_q11_q50
    s_t3_1_q11_q50 = -x59
    x103 = P31*s_t3_1_q11_q50
    x104 = -x102*x53 + x103*x56
    x105 = x102*x56 + x103*x53
    x106 = (1.0 / (jnp.hypot(-x104, x105)))
    x107 = c_th14_q11_q50*x104 + s_th14_q11_q50*x105
    x108 = c_th14_q11_q50*x105 - s_th14_q11_q50*x104
    c_t3_0_q11_q51 = c5*(c6 + x64)
    x109 = P21 + P31*c_t3_0_q11_q51
    s_t3_0_q11_q51 = x66
    x110 = P31*s_t3_0_q11_q51
    x111 = -x109*x62 + x110*x63
    x112 = x109*x63 + x110*x62
    x113 = (1.0 / (jnp.hypot(-x111, x112)))
    x114 = c_th14_q11_q51*x111 + s_th14_q11_q51*x112
    x115 = c_th14_q11_q51*x112 - s_th14_q11_q51*x111
    x116 = P21 + P31*c_t3_0_q11_q51
    s_t3_1_q11_q51 = -x66
    x117 = P31*s_t3_1_q11_q51
    x118 = -x116*x62 + x117*x63
    x119 = x116*x63 + x117*x62
    x120 = (1.0 / (jnp.hypot(-x118, x119)))
    x121 = c_th14_q11_q51*x118 + s_th14_q11_q51*x119
    x122 = c_th14_q11_q51*x119 - s_th14_q11_q51*x118
    c_t5_0_q10 = c_t1_0*r22 - r12*s_t1_0
    s_q6_q10_q50 = x23*x26
    c_q6_q10_q50 = -x24*x26
    s_q6_q10_q51 = x23*x37
    c_q6_q10_q51 = -x24*x37
    c_t5_0_q11 = c_t1_1*r22 - r12*s_t1_1
    s_q6_q11_q50 = x49*x52
    c_q6_q11_q50 = -x50*x52
    s_q6_q11_q51 = x49*x61
    c_q6_q11_q51 = -x50*x61
    s_q2_b000 = x69*x71
    c_q2_b000 = -x70*x71
    s_q4_b000 = -x71*(c_t3_0_q10_q50*x72 - s_t3_0_q10_q50*x73)
    c_q4_b000 = -x71*(c_t3_0_q10_q50*x73 + s_t3_0_q10_q50*x72)
    s_q2_b001 = x76*x78
    c_q2_b001 = -x77*x78
    s_q4_b001 = -x78*(c_t3_0_q10_q50*x79 - s_t3_1_q10_q50*x80)
    c_q4_b001 = -x78*(c_t3_0_q10_q50*x80 + s_t3_1_q10_q50*x79)
    s_q2_b010 = x83*x85
    c_q2_b010 = -x84*x85
    s_q4_b010 = -x85*(c_t3_0_q10_q51*x86 - s_t3_0_q10_q51*x87)
    c_q4_b010 = -x85*(c_t3_0_q10_q51*x87 + s_t3_0_q10_q51*x86)
    s_q2_b011 = x90*x92
    c_q2_b011 = -x91*x92
    s_q4_b011 = -x92*(c_t3_0_q10_q51*x93 - s_t3_1_q10_q51*x94)
    c_q4_b011 = -x92*(c_t3_0_q10_q51*x94 + s_t3_1_q10_q51*x93)
    s_q2_b100 = x97*x99
    c_q2_b100 = -x98*x99
    s_q4_b100 = -x99*(c_t3_0_q11_q50*x100 - s_t3_0_q11_q50*x101)
    c_q4_b100 = -x99*(c_t3_0_q11_q50*x101 + s_t3_0_q11_q50*x100)
    s_q2_b101 = x104*x106
    c_q2_b101 = -x105*x106
    s_q4_b101 = -x106*(c_t3_0_q11_q50*x107 - s_t3_1_q11_q50*x108)
    c_q4_b101 = -x106*(c_t3_0_q11_q50*x108 + s_t3_1_q11_q50*x107)
    s_q2_b110 = x111*x113
    c_q2_b110 = -x112*x113
    s_q4_b110 = -x113*(c_t3_0_q11_q51*x114 - s_t3_0_q11_q51*x115)
    c_q4_b110 = -x113*(c_t3_0_q11_q51*x115 + s_t3_0_q11_q51*x114)
    s_q2_b111 = x118*x120
    c_q2_b111 = -x119*x120
    s_q4_b111 = -x120*(c_t3_0_q11_q51*x121 - s_t3_1_q11_q51*x122)
    c_q4_b111 = -x120*(c_t3_0_q11_q51*x122 + s_t3_1_q11_q51*x121)

    # ── aliases ──
    c_t5_1_q10 = c_t5_0_q10
    c_t3_1_q10_q50 = c_t3_0_q10_q50
    c_t3_1_q10_q51 = c_t3_0_q10_q51
    c_t5_1_q11 = c_t5_0_q11
    c_t3_1_q11_q50 = c_t3_0_q11_q50
    c_t3_1_q11_q51 = c_t3_0_q11_q51

    sq = jnp.array([
        [s_t1_0, s_t1_0, s_t1_0, s_t1_0, s_t1_1, s_t1_1, s_t1_1, s_t1_1],
        [s_q2_b000, s_q2_b001, s_q2_b010, s_q2_b011, s_q2_b100, s_q2_b101, s_q2_b110, s_q2_b111],
        [s_t3_0_q10_q50, s_t3_1_q10_q50, s_t3_0_q10_q51, s_t3_1_q10_q51, s_t3_0_q11_q50, s_t3_1_q11_q50, s_t3_0_q11_q51, s_t3_1_q11_q51],
        [s_q4_b000, s_q4_b001, s_q4_b010, s_q4_b011, s_q4_b100, s_q4_b101, s_q4_b110, s_q4_b111],
        [s_t5_0_q10, s_t5_0_q10, s_t5_1_q10, s_t5_1_q10, s_t5_0_q11, s_t5_0_q11, s_t5_1_q11, s_t5_1_q11],
        [s_q6_q10_q50, s_q6_q10_q50, s_q6_q10_q51, s_q6_q10_q51, s_q6_q11_q50, s_q6_q11_q50, s_q6_q11_q51, s_q6_q11_q51],
    ])  # (6, 8)
    cq = jnp.array([
        [c_t1_0, c_t1_0, c_t1_0, c_t1_0, c_t1_1, c_t1_1, c_t1_1, c_t1_1],
        [c_q2_b000, c_q2_b001, c_q2_b010, c_q2_b011, c_q2_b100, c_q2_b101, c_q2_b110, c_q2_b111],
        [c_t3_0_q10_q50, c_t3_1_q10_q50, c_t3_0_q10_q51, c_t3_1_q10_q51, c_t3_0_q11_q50, c_t3_1_q11_q50, c_t3_0_q11_q51, c_t3_1_q11_q51],
        [c_q4_b000, c_q4_b001, c_q4_b010, c_q4_b011, c_q4_b100, c_q4_b101, c_q4_b110, c_q4_b111],
        [c_t5_0_q10, c_t5_0_q10, c_t5_1_q10, c_t5_1_q10, c_t5_0_q11, c_t5_0_q11, c_t5_1_q11, c_t5_1_q11],
        [c_q6_q10_q50, c_q6_q10_q50, c_q6_q10_q51, c_q6_q10_q51, c_q6_q11_q50, c_q6_q11_q50, c_q6_q11_q51, c_q6_q11_q51],
    ])  # (6, 8)
    valid = ~(jnp.isnan(sq) | jnp.isnan(cq)).any(axis=0)
    return sq, cq, valid
